// src/index.ts
import "dotenv/config";

// src/app.ts
import express6 from "express";
import cors from "cors";
import { toNodeHandler } from "better-auth/node";

// src/lib/auth.ts
import { betterAuth } from "better-auth";
import { prismaAdapter } from "better-auth/adapters/prisma";

// src/lib/prisma.ts
import "dotenv/config";
import { PrismaPg } from "@prisma/adapter-pg";

// generated/prisma/client.ts
import * as path from "path";
import { fileURLToPath } from "url";

// generated/prisma/internal/class.ts
import * as runtime from "@prisma/client/runtime/client";
var config = {
  "previewFeatures": [],
  "clientVersion": "7.4.1",
  "engineVersion": "55ae170b1ced7fc6ed07a15f110549408c501bb3",
  "activeProvider": "postgresql",
  "inlineSchema": '// This is your Prisma schema file,\n// learn more about it in the docs: https://pris.ly/d/prisma-schema\n\n// Looking for ways to speed up your queries, or scale easily with your serverless or edge functions?\n// Try Prisma Accelerate: https://pris.ly/cli/accelerate-init\n\ngenerator client {\n  provider = "prisma-client"\n  output   = "../../generated/prisma"\n}\n\ndatasource db {\n  provider = "postgresql"\n}\n\nmodel User {\n  id    String @id @default(uuid())\n  email String @unique\n\n  name   String?\n  role   Role       @default(STUDENT)\n  image  String?\n  status UserStatus @default(ACTIVE)\n\n  tutorProfile TutorProfile?\n  bookings     Booking[]     @relation("StudentBookings")\n  reviews      Review[]\n\n  sessions      Session[]\n  accounts      Account[]\n  emailVerified Boolean   @default(false)\n  createdAt     DateTime  @default(now())\n  updatedAt     DateTime  @updatedAt\n}\n\nmodel TutorProfile {\n  id         Int    @id @default(autoincrement())\n  bio        String\n  hourlyRate Float\n\n  user   User   @relation(fields: [userId], references: [id])\n  userId String @unique\n\n  status TutorStatus @default(AVAILABLE)\n\n  categories   TutorCategory[]\n  bookings     Booking[]           @relation("TutorBookings")\n  reviews      Review[]\n  availability TutorAvailability[]\n\n  createdAt DateTime @default(now())\n  updatedAt DateTime @updatedAt\n}\n\nmodel Category {\n  id   Int    @id @default(autoincrement())\n  name String @unique\n\n  tutors TutorCategory[]\n}\n\nmodel TutorCategory {\n  tutorProfile   TutorProfile @relation(fields: [tutorProfileId], references: [id])\n  tutorProfileId Int\n\n  category   Category @relation(fields: [categoryId], references: [id])\n  categoryId Int\n\n  @@id([tutorProfileId, categoryId])\n}\n\nmodel TutorAvailability {\n  id        Int          @id @default(autoincrement())\n  tutorId   Int\n  tutor     TutorProfile @relation(fields: [tutorId], references: [id], onDelete: Cascade)\n  dayOfWeek Int\n  startTime String\n  endTime   String\n  createdAt DateTime     @default(now())\n\n  @@unique([tutorId, dayOfWeek])\n}\n\nmodel Booking {\n  id Int @id @default(autoincrement())\n\n  student   User   @relation("StudentBookings", fields: [studentId], references: [id])\n  studentId String\n\n  tutor   TutorProfile @relation("TutorBookings", fields: [tutorId], references: [id])\n  tutorId Int\n\n  scheduledAt DateTime\n  status      BookingStatus @default(PENDING)\n  review      Review?\n  createdAt   DateTime      @default(now())\n}\n\nmodel Review {\n  id Int @id @default(autoincrement())\n\n  rating  Int\n  comment String?\n\n  student   User   @relation(fields: [studentId], references: [id])\n  studentId String\n\n  tutor   TutorProfile @relation(fields: [tutorId], references: [id])\n  tutorId Int\n\n  booking   Booking @relation(fields: [bookingId], references: [id])\n  bookingId Int     @unique\n\n  createdAt DateTime @default(now())\n}\n\nmodel Session {\n  id String @id @default(uuid())\n\n  expiresAt DateTime\n  token     String   @unique\n\n  ipAddress String?\n  userAgent String?\n\n  userId String\n  user   User   @relation(fields: [userId], references: [id], onDelete: Cascade)\n\n  createdAt DateTime @default(now())\n  updatedAt DateTime @updatedAt\n}\n\nmodel Account {\n  id         String @id @default(uuid())\n  providerId String\n  accountId  String\n\n  userId                String\n  user                  User      @relation(fields: [userId], references: [id], onDelete: Cascade)\n  password              String?\n  accessToken           String?\n  refreshToken          String?\n  idToken               String?\n  accessTokenExpiresAt  DateTime?\n  refreshTokenExpiresAt DateTime?\n  scope                 String?\n  createdAt             DateTime  @default(now())\n  updatedAt             DateTime  @updatedAt\n}\n\nmodel Verification {\n  id         String   @id @default(uuid())\n  identifier String\n  value      String\n  expiresAt  DateTime\n\n  createdAt DateTime @default(now())\n  updatedAt DateTime @updatedAt\n}\n\nenum Role {\n  STUDENT\n  TUTOR\n  ADMIN\n}\n\nenum UserStatus {\n  ACTIVE\n  BANNED\n}\n\nenum BookingStatus {\n  PENDING\n  CONFIRMED\n  COMPLETED\n  CANCELLED\n}\n\nenum TutorStatus {\n  AVAILABLE\n  BUSY\n  OFFLINE\n}\n',
  "runtimeDataModel": {
    "models": {},
    "enums": {},
    "types": {}
  },
  "parameterizationSchema": {
    "strings": [],
    "graph": ""
  }
};
config.runtimeDataModel = JSON.parse('{"models":{"User":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"email","kind":"scalar","type":"String"},{"name":"name","kind":"scalar","type":"String"},{"name":"role","kind":"enum","type":"Role"},{"name":"image","kind":"scalar","type":"String"},{"name":"status","kind":"enum","type":"UserStatus"},{"name":"tutorProfile","kind":"object","type":"TutorProfile","relationName":"TutorProfileToUser"},{"name":"bookings","kind":"object","type":"Booking","relationName":"StudentBookings"},{"name":"reviews","kind":"object","type":"Review","relationName":"ReviewToUser"},{"name":"sessions","kind":"object","type":"Session","relationName":"SessionToUser"},{"name":"accounts","kind":"object","type":"Account","relationName":"AccountToUser"},{"name":"emailVerified","kind":"scalar","type":"Boolean"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"}],"dbName":null},"TutorProfile":{"fields":[{"name":"id","kind":"scalar","type":"Int"},{"name":"bio","kind":"scalar","type":"String"},{"name":"hourlyRate","kind":"scalar","type":"Float"},{"name":"user","kind":"object","type":"User","relationName":"TutorProfileToUser"},{"name":"userId","kind":"scalar","type":"String"},{"name":"status","kind":"enum","type":"TutorStatus"},{"name":"categories","kind":"object","type":"TutorCategory","relationName":"TutorCategoryToTutorProfile"},{"name":"bookings","kind":"object","type":"Booking","relationName":"TutorBookings"},{"name":"reviews","kind":"object","type":"Review","relationName":"ReviewToTutorProfile"},{"name":"availability","kind":"object","type":"TutorAvailability","relationName":"TutorAvailabilityToTutorProfile"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"}],"dbName":null},"Category":{"fields":[{"name":"id","kind":"scalar","type":"Int"},{"name":"name","kind":"scalar","type":"String"},{"name":"tutors","kind":"object","type":"TutorCategory","relationName":"CategoryToTutorCategory"}],"dbName":null},"TutorCategory":{"fields":[{"name":"tutorProfile","kind":"object","type":"TutorProfile","relationName":"TutorCategoryToTutorProfile"},{"name":"tutorProfileId","kind":"scalar","type":"Int"},{"name":"category","kind":"object","type":"Category","relationName":"CategoryToTutorCategory"},{"name":"categoryId","kind":"scalar","type":"Int"}],"dbName":null},"TutorAvailability":{"fields":[{"name":"id","kind":"scalar","type":"Int"},{"name":"tutorId","kind":"scalar","type":"Int"},{"name":"tutor","kind":"object","type":"TutorProfile","relationName":"TutorAvailabilityToTutorProfile"},{"name":"dayOfWeek","kind":"scalar","type":"Int"},{"name":"startTime","kind":"scalar","type":"String"},{"name":"endTime","kind":"scalar","type":"String"},{"name":"createdAt","kind":"scalar","type":"DateTime"}],"dbName":null},"Booking":{"fields":[{"name":"id","kind":"scalar","type":"Int"},{"name":"student","kind":"object","type":"User","relationName":"StudentBookings"},{"name":"studentId","kind":"scalar","type":"String"},{"name":"tutor","kind":"object","type":"TutorProfile","relationName":"TutorBookings"},{"name":"tutorId","kind":"scalar","type":"Int"},{"name":"scheduledAt","kind":"scalar","type":"DateTime"},{"name":"status","kind":"enum","type":"BookingStatus"},{"name":"review","kind":"object","type":"Review","relationName":"BookingToReview"},{"name":"createdAt","kind":"scalar","type":"DateTime"}],"dbName":null},"Review":{"fields":[{"name":"id","kind":"scalar","type":"Int"},{"name":"rating","kind":"scalar","type":"Int"},{"name":"comment","kind":"scalar","type":"String"},{"name":"student","kind":"object","type":"User","relationName":"ReviewToUser"},{"name":"studentId","kind":"scalar","type":"String"},{"name":"tutor","kind":"object","type":"TutorProfile","relationName":"ReviewToTutorProfile"},{"name":"tutorId","kind":"scalar","type":"Int"},{"name":"booking","kind":"object","type":"Booking","relationName":"BookingToReview"},{"name":"bookingId","kind":"scalar","type":"Int"},{"name":"createdAt","kind":"scalar","type":"DateTime"}],"dbName":null},"Session":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"expiresAt","kind":"scalar","type":"DateTime"},{"name":"token","kind":"scalar","type":"String"},{"name":"ipAddress","kind":"scalar","type":"String"},{"name":"userAgent","kind":"scalar","type":"String"},{"name":"userId","kind":"scalar","type":"String"},{"name":"user","kind":"object","type":"User","relationName":"SessionToUser"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"}],"dbName":null},"Account":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"providerId","kind":"scalar","type":"String"},{"name":"accountId","kind":"scalar","type":"String"},{"name":"userId","kind":"scalar","type":"String"},{"name":"user","kind":"object","type":"User","relationName":"AccountToUser"},{"name":"password","kind":"scalar","type":"String"},{"name":"accessToken","kind":"scalar","type":"String"},{"name":"refreshToken","kind":"scalar","type":"String"},{"name":"idToken","kind":"scalar","type":"String"},{"name":"accessTokenExpiresAt","kind":"scalar","type":"DateTime"},{"name":"refreshTokenExpiresAt","kind":"scalar","type":"DateTime"},{"name":"scope","kind":"scalar","type":"String"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"}],"dbName":null},"Verification":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"identifier","kind":"scalar","type":"String"},{"name":"value","kind":"scalar","type":"String"},{"name":"expiresAt","kind":"scalar","type":"DateTime"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"}],"dbName":null}},"enums":{},"types":{}}');
config.parameterizationSchema = {
  strings: JSON.parse('["where","user","orderBy","cursor","tutorProfile","tutors","_count","category","categories","student","tutor","booking","review","bookings","reviews","availability","sessions","accounts","User.findUnique","User.findUniqueOrThrow","User.findFirst","User.findFirstOrThrow","User.findMany","data","User.createOne","User.createMany","User.createManyAndReturn","User.updateOne","User.updateMany","User.updateManyAndReturn","create","update","User.upsertOne","User.deleteOne","User.deleteMany","having","_min","_max","User.groupBy","User.aggregate","TutorProfile.findUnique","TutorProfile.findUniqueOrThrow","TutorProfile.findFirst","TutorProfile.findFirstOrThrow","TutorProfile.findMany","TutorProfile.createOne","TutorProfile.createMany","TutorProfile.createManyAndReturn","TutorProfile.updateOne","TutorProfile.updateMany","TutorProfile.updateManyAndReturn","TutorProfile.upsertOne","TutorProfile.deleteOne","TutorProfile.deleteMany","_avg","_sum","TutorProfile.groupBy","TutorProfile.aggregate","Category.findUnique","Category.findUniqueOrThrow","Category.findFirst","Category.findFirstOrThrow","Category.findMany","Category.createOne","Category.createMany","Category.createManyAndReturn","Category.updateOne","Category.updateMany","Category.updateManyAndReturn","Category.upsertOne","Category.deleteOne","Category.deleteMany","Category.groupBy","Category.aggregate","TutorCategory.findUnique","TutorCategory.findUniqueOrThrow","TutorCategory.findFirst","TutorCategory.findFirstOrThrow","TutorCategory.findMany","TutorCategory.createOne","TutorCategory.createMany","TutorCategory.createManyAndReturn","TutorCategory.updateOne","TutorCategory.updateMany","TutorCategory.updateManyAndReturn","TutorCategory.upsertOne","TutorCategory.deleteOne","TutorCategory.deleteMany","TutorCategory.groupBy","TutorCategory.aggregate","TutorAvailability.findUnique","TutorAvailability.findUniqueOrThrow","TutorAvailability.findFirst","TutorAvailability.findFirstOrThrow","TutorAvailability.findMany","TutorAvailability.createOne","TutorAvailability.createMany","TutorAvailability.createManyAndReturn","TutorAvailability.updateOne","TutorAvailability.updateMany","TutorAvailability.updateManyAndReturn","TutorAvailability.upsertOne","TutorAvailability.deleteOne","TutorAvailability.deleteMany","TutorAvailability.groupBy","TutorAvailability.aggregate","Booking.findUnique","Booking.findUniqueOrThrow","Booking.findFirst","Booking.findFirstOrThrow","Booking.findMany","Booking.createOne","Booking.createMany","Booking.createManyAndReturn","Booking.updateOne","Booking.updateMany","Booking.updateManyAndReturn","Booking.upsertOne","Booking.deleteOne","Booking.deleteMany","Booking.groupBy","Booking.aggregate","Review.findUnique","Review.findUniqueOrThrow","Review.findFirst","Review.findFirstOrThrow","Review.findMany","Review.createOne","Review.createMany","Review.createManyAndReturn","Review.updateOne","Review.updateMany","Review.updateManyAndReturn","Review.upsertOne","Review.deleteOne","Review.deleteMany","Review.groupBy","Review.aggregate","Session.findUnique","Session.findUniqueOrThrow","Session.findFirst","Session.findFirstOrThrow","Session.findMany","Session.createOne","Session.createMany","Session.createManyAndReturn","Session.updateOne","Session.updateMany","Session.updateManyAndReturn","Session.upsertOne","Session.deleteOne","Session.deleteMany","Session.groupBy","Session.aggregate","Account.findUnique","Account.findUniqueOrThrow","Account.findFirst","Account.findFirstOrThrow","Account.findMany","Account.createOne","Account.createMany","Account.createManyAndReturn","Account.updateOne","Account.updateMany","Account.updateManyAndReturn","Account.upsertOne","Account.deleteOne","Account.deleteMany","Account.groupBy","Account.aggregate","Verification.findUnique","Verification.findUniqueOrThrow","Verification.findFirst","Verification.findFirstOrThrow","Verification.findMany","Verification.createOne","Verification.createMany","Verification.createManyAndReturn","Verification.updateOne","Verification.updateMany","Verification.updateManyAndReturn","Verification.upsertOne","Verification.deleteOne","Verification.deleteMany","Verification.groupBy","Verification.aggregate","AND","OR","NOT","id","identifier","value","expiresAt","createdAt","updatedAt","equals","in","notIn","lt","lte","gt","gte","not","contains","startsWith","endsWith","providerId","accountId","userId","password","accessToken","refreshToken","idToken","accessTokenExpiresAt","refreshTokenExpiresAt","scope","token","ipAddress","userAgent","rating","comment","studentId","tutorId","bookingId","scheduledAt","BookingStatus","status","dayOfWeek","startTime","endTime","tutorProfileId","categoryId","name","every","some","none","bio","hourlyRate","TutorStatus","email","Role","role","image","UserStatus","emailVerified","tutorId_dayOfWeek","tutorProfileId_categoryId","is","isNot","connectOrCreate","upsert","disconnect","delete","connect","createMany","set","updateMany","deleteMany","increment","decrement","multiply","divide"]'),
  graph: "9wRgoAERBAAAzQIAIA0AALsCACAOAAC8AgAgEAAAzgIAIBEAAM8CACC6AQAAyAIAMLsBAAArABC8AQAAyAIAML0BAQAAAAHBAUAAmQIAIcIBQACZAgAh4gEAAMsC9AEi6AEBAMkCACHvAQEAAAAB8QEAAMoC8QEi8gEBAMkCACH0ASAAzAIAIQEAAAABACAPAQAAugIAIAgAALACACANAAC7AgAgDgAAvAIAIA8AAL0CACC6AQAAtwIAMLsBAAADABC8AQAAtwIAML0BAgCvAgAhwQFAAJkCACHCAUAAmQIAIdABAQCYAgAh4gEAALkC7wEi7AEBAJgCACHtAQgAuAIAIQEAAAADACAHBAAA1QIAIAcAAN0CACC6AQAA3AIAMLsBAAAFABC8AQAA3AIAMOYBAgCvAgAh5wECAK8CACECBAAAsgQAIAcAALcEACAIBAAA1QIAIAcAAN0CACC6AQAA3AIAMLsBAAAFABC8AQAA3AIAMOYBAgCvAgAh5wECAK8CACH2AQAA2wIAIAMAAAAFACACAAAGADADAAAHACADAAAABQAgAgAABgAwAwAABwAgAQAAAAUAIAwJAAC6AgAgCgAA1QIAIAwAANoCACC6AQAA2AIAMLsBAAALABC8AQAA2AIAML0BAgCvAgAhwQFAAJkCACHdAQEAmAIAId4BAgCvAgAh4AFAAJkCACHiAQAA2QLiASIDCQAA7wMAIAoAALIEACAMAAC2BAAgDAkAALoCACAKAADVAgAgDAAA2gIAILoBAADYAgAwuwEAAAsAELwBAADYAgAwvQECAAAAAcEBQACZAgAh3QEBAJgCACHeAQIArwIAIeABQACZAgAh4gEAANkC4gEiAwAAAAsAIAIAAAwAMAMAAA0AIA0JAAC6AgAgCgAA1QIAIAsAANcCACC6AQAA1gIAMLsBAAAPABC8AQAA1gIAML0BAgCvAgAhwQFAAJkCACHbAQIArwIAIdwBAQDJAgAh3QEBAJgCACHeAQIArwIAId8BAgCvAgAhAQAAAA8AIAQJAADvAwAgCgAAsgQAIAsAALUEACDcAQAA4wIAIA0JAAC6AgAgCgAA1QIAIAsAANcCACC6AQAA1gIAMLsBAAAPABC8AQAA1gIAML0BAgAAAAHBAUAAmQIAIdsBAgCvAgAh3AEBAMkCACHdAQEAmAIAId4BAgCvAgAh3wECAAAAAQMAAAAPACACAAARADADAAASACAKCgAA1QIAILoBAADUAgAwuwEAABQAELwBAADUAgAwvQECAK8CACHBAUAAmQIAId4BAgCvAgAh4wECAK8CACHkAQEAmAIAIeUBAQCYAgAhAQoAALIEACALCgAA1QIAILoBAADUAgAwuwEAABQAELwBAADUAgAwvQECAAAAAcEBQACZAgAh3gECAK8CACHjAQIArwIAIeQBAQCYAgAh5QEBAJgCACH1AQAA0wIAIAMAAAAUACACAAAVADADAAAWACABAAAABQAgAQAAAAsAIAEAAAAPACABAAAAFAAgAwAAAAsAIAIAAAwAMAMAAA0AIAMAAAAPACACAAARADADAAASACAMAQAAugIAILoBAADSAgAwuwEAAB4AELwBAADSAgAwvQEBAJgCACHAAUAAmQIAIcEBQACZAgAhwgFAAJkCACHQAQEAmAIAIdgBAQCYAgAh2QEBAMkCACHaAQEAyQIAIQMBAADvAwAg2QEAAOMCACDaAQAA4wIAIAwBAAC6AgAgugEAANICADC7AQAAHgAQvAEAANICADC9AQEAAAABwAFAAJkCACHBAUAAmQIAIcIBQACZAgAh0AEBAJgCACHYAQEAAAAB2QEBAMkCACHaAQEAyQIAIQMAAAAeACACAAAfADADAAAgACARAQAAugIAILoBAADQAgAwuwEAACIAELwBAADQAgAwvQEBAJgCACHBAUAAmQIAIcIBQACZAgAhzgEBAJgCACHPAQEAmAIAIdABAQCYAgAh0QEBAMkCACHSAQEAyQIAIdMBAQDJAgAh1AEBAMkCACHVAUAA0QIAIdYBQADRAgAh1wEBAMkCACEIAQAA7wMAINEBAADjAgAg0gEAAOMCACDTAQAA4wIAINQBAADjAgAg1QEAAOMCACDWAQAA4wIAINcBAADjAgAgEQEAALoCACC6AQAA0AIAMLsBAAAiABC8AQAA0AIAML0BAQAAAAHBAUAAmQIAIcIBQACZAgAhzgEBAJgCACHPAQEAmAIAIdABAQCYAgAh0QEBAMkCACHSAQEAyQIAIdMBAQDJAgAh1AEBAMkCACHVAUAA0QIAIdYBQADRAgAh1wEBAMkCACEDAAAAIgAgAgAAIwAwAwAAJAAgAQAAAAsAIAEAAAAPACABAAAAHgAgAQAAACIAIAEAAAABACARBAAAzQIAIA0AALsCACAOAAC8AgAgEAAAzgIAIBEAAM8CACC6AQAAyAIAMLsBAAArABC8AQAAyAIAML0BAQCYAgAhwQFAAJkCACHCAUAAmQIAIeIBAADLAvQBIugBAQDJAgAh7wEBAJgCACHxAQAAygLxASLyAQEAyQIAIfQBIADMAgAhBwQAALIEACANAADwAwAgDgAA8QMAIBAAALMEACARAAC0BAAg6AEAAOMCACDyAQAA4wIAIAMAAAArACACAAAsADADAAABACADAAAAKwAgAgAALAAwAwAAAQAgAwAAACsAIAIAACwAMAMAAAEAIA4EAACtBAAgDQAArgQAIA4AAK8EACAQAACwBAAgEQAAsQQAIL0BAQAAAAHBAUAAAAABwgFAAAAAAeIBAAAA9AEC6AEBAAAAAe8BAQAAAAHxAQAAAPEBAvIBAQAAAAH0ASAAAAABARcAADAAIAm9AQEAAAABwQFAAAAAAcIBQAAAAAHiAQAAAPQBAugBAQAAAAHvAQEAAAAB8QEAAADxAQLyAQEAAAAB9AEgAAAAAQEXAAAyADABFwAAMgAwDgQAAPkDACANAAD6AwAgDgAA-wMAIBAAAPwDACARAAD9AwAgvQEBAOECACHBAUAA4gIAIcIBQADiAgAh4gEAAPcD9AEi6AEBAOcCACHvAQEA4QIAIfEBAAD2A_EBIvIBAQDnAgAh9AEgAPgDACECAAAAAQAgFwAANQAgCb0BAQDhAgAhwQFAAOICACHCAUAA4gIAIeIBAAD3A_QBIugBAQDnAgAh7wEBAOECACHxAQAA9gPxASLyAQEA5wIAIfQBIAD4AwAhAgAAACsAIBcAADcAIAIAAAArACAXAAA3ACADAAAAAQAgHgAAMAAgHwAANQAgAQAAAAEAIAEAAAArACAFBgAA8wMAICQAAPUDACAlAAD0AwAg6AEAAOMCACDyAQAA4wIAIAy6AQAAvgIAMLsBAAA-ABC8AQAAvgIAML0BAQCQAgAhwQFAAJECACHCAUAAkQIAIeIBAADAAvQBIugBAQCbAgAh7wEBAJACACHxAQAAvwLxASLyAQEAmwIAIfQBIADBAgAhAwAAACsAIAIAAD0AMCMAAD4AIAMAAAArACACAAAsADADAAABACAPAQAAugIAIAgAALACACANAAC7AgAgDgAAvAIAIA8AAL0CACC6AQAAtwIAMLsBAAADABC8AQAAtwIAML0BAgAAAAHBAUAAmQIAIcIBQACZAgAh0AEBAAAAAeIBAAC5Au8BIuwBAQCYAgAh7QEIALgCACEBAAAAQQAgAQAAAEEAIAUBAADvAwAgCAAAsAMAIA0AAPADACAOAADxAwAgDwAA8gMAIAMAAAADACACAABEADADAABBACADAAAAAwAgAgAARAAwAwAAQQAgAwAAAAMAIAIAAEQAMAMAAEEAIAwBAADqAwAgCAAA6wMAIA0AAOwDACAOAADtAwAgDwAA7gMAIL0BAgAAAAHBAUAAAAABwgFAAAAAAdABAQAAAAHiAQAAAO8BAuwBAQAAAAHtAQgAAAABARcAAEgAIAe9AQIAAAABwQFAAAAAAcIBQAAAAAHQAQEAAAAB4gEAAADvAQLsAQEAAAAB7QEIAAAAAQEXAABKADABFwAASgAwDAEAALgDACAIAAC5AwAgDQAAugMAIA4AALsDACAPAAC8AwAgvQECAPUCACHBAUAA4gIAIcIBQADiAgAh0AEBAOECACHiAQAAtwPvASLsAQEA4QIAIe0BCAC2AwAhAgAAAEEAIBcAAE0AIAe9AQIA9QIAIcEBQADiAgAhwgFAAOICACHQAQEA4QIAIeIBAAC3A-8BIuwBAQDhAgAh7QEIALYDACECAAAAAwAgFwAATwAgAgAAAAMAIBcAAE8AIAMAAABBACAeAABIACAfAABNACABAAAAQQAgAQAAAAMAIAUGAACxAwAgJAAAtAMAICUAALMDACA2AACyAwAgNwAAtQMAIAq6AQAAsQIAMLsBAABWABC8AQAAsQIAML0BAgCkAgAhwQFAAJECACHCAUAAkQIAIdABAQCQAgAh4gEAALMC7wEi7AEBAJACACHtAQgAsgIAIQMAAAADACACAABVADAjAABWACADAAAAAwAgAgAARAAwAwAAQQAgBgUAALACACC6AQAArgIAMLsBAABcABC8AQAArgIAML0BAgAAAAHoAQEAAAABAQAAAFkAIAEAAABZACAGBQAAsAIAILoBAACuAgAwuwEAAFwAELwBAACuAgAwvQECAK8CACHoAQEAmAIAIQEFAACwAwAgAwAAAFwAIAIAAF0AMAMAAFkAIAMAAABcACACAABdADADAABZACADAAAAXAAgAgAAXQAwAwAAWQAgAwUAAK8DACC9AQIAAAAB6AEBAAAAAQEXAABhACACvQECAAAAAegBAQAAAAEBFwAAYwAwARcAAGMAMAMFAACiAwAgvQECAPUCACHoAQEA4QIAIQIAAABZACAXAABmACACvQECAPUCACHoAQEA4QIAIQIAAABcACAXAABoACACAAAAXAAgFwAAaAAgAwAAAFkAIB4AAGEAIB8AAGYAIAEAAABZACABAAAAXAAgBQYAAJ0DACAkAACgAwAgJQAAnwMAIDYAAJ4DACA3AAChAwAgBboBAACtAgAwuwEAAG8AELwBAACtAgAwvQECAKQCACHoAQEAkAIAIQMAAABcACACAABuADAjAABvACADAAAAXAAgAgAAXQAwAwAAWQAgAQAAAAcAIAEAAAAHACADAAAABQAgAgAABgAwAwAABwAgAwAAAAUAIAIAAAYAMAMAAAcAIAMAAAAFACACAAAGADADAAAHACAEBAAAmwMAIAcAAJwDACDmAQIAAAAB5wECAAAAAQEXAAB3ACAC5gECAAAAAecBAgAAAAEBFwAAeQAwARcAAHkAMAQEAACZAwAgBwAAmgMAIOYBAgD1AgAh5wECAPUCACECAAAABwAgFwAAfAAgAuYBAgD1AgAh5wECAPUCACECAAAABQAgFwAAfgAgAgAAAAUAIBcAAH4AIAMAAAAHACAeAAB3ACAfAAB8ACABAAAABwAgAQAAAAUAIAUGAACUAwAgJAAAlwMAICUAAJYDACA2AACVAwAgNwAAmAMAIAW6AQAArAIAMLsBAACFAQAQvAEAAKwCADDmAQIApAIAIecBAgCkAgAhAwAAAAUAIAIAAIQBADAjAACFAQAgAwAAAAUAIAIAAAYAMAMAAAcAIAEAAAAWACABAAAAFgAgAwAAABQAIAIAABUAMAMAABYAIAMAAAAUACACAAAVADADAAAWACADAAAAFAAgAgAAFQAwAwAAFgAgBwoAAJMDACC9AQIAAAABwQFAAAAAAd4BAgAAAAHjAQIAAAAB5AEBAAAAAeUBAQAAAAEBFwAAjQEAIAa9AQIAAAABwQFAAAAAAd4BAgAAAAHjAQIAAAAB5AEBAAAAAeUBAQAAAAEBFwAAjwEAMAEXAACPAQAwBwoAAJIDACC9AQIA9QIAIcEBQADiAgAh3gECAPUCACHjAQIA9QIAIeQBAQDhAgAh5QEBAOECACECAAAAFgAgFwAAkgEAIAa9AQIA9QIAIcEBQADiAgAh3gECAPUCACHjAQIA9QIAIeQBAQDhAgAh5QEBAOECACECAAAAFAAgFwAAlAEAIAIAAAAUACAXAACUAQAgAwAAABYAIB4AAI0BACAfAACSAQAgAQAAABYAIAEAAAAUACAFBgAAjQMAICQAAJADACAlAACPAwAgNgAAjgMAIDcAAJEDACAJugEAAKsCADC7AQAAmwEAELwBAACrAgAwvQECAKQCACHBAUAAkQIAId4BAgCkAgAh4wECAKQCACHkAQEAkAIAIeUBAQCQAgAhAwAAABQAIAIAAJoBADAjAACbAQAgAwAAABQAIAIAABUAMAMAABYAIAEAAAANACABAAAADQAgAwAAAAsAIAIAAAwAMAMAAA0AIAMAAAALACACAAAMADADAAANACADAAAACwAgAgAADAAwAwAADQAgCQkAAIoDACAKAACLAwAgDAAAjAMAIL0BAgAAAAHBAUAAAAAB3QEBAAAAAd4BAgAAAAHgAUAAAAAB4gEAAADiAQIBFwAAowEAIAa9AQIAAAABwQFAAAAAAd0BAQAAAAHeAQIAAAAB4AFAAAAAAeIBAAAA4gECARcAAKUBADABFwAApQEAMAkJAACCAwAgCgAAgwMAIAwAAIQDACC9AQIA9QIAIcEBQADiAgAh3QEBAOECACHeAQIA9QIAIeABQADiAgAh4gEAAIED4gEiAgAAAA0AIBcAAKgBACAGvQECAPUCACHBAUAA4gIAId0BAQDhAgAh3gECAPUCACHgAUAA4gIAIeIBAACBA-IBIgIAAAALACAXAACqAQAgAgAAAAsAIBcAAKoBACADAAAADQAgHgAAowEAIB8AAKgBACABAAAADQAgAQAAAAsAIAUGAAD8AgAgJAAA_wIAICUAAP4CACA2AAD9AgAgNwAAgAMAIAm6AQAApwIAMLsBAACxAQAQvAEAAKcCADC9AQIApAIAIcEBQACRAgAh3QEBAJACACHeAQIApAIAIeABQACRAgAh4gEAAKgC4gEiAwAAAAsAIAIAALABADAjAACxAQAgAwAAAAsAIAIAAAwAMAMAAA0AIAEAAAASACABAAAAEgAgAwAAAA8AIAIAABEAMAMAABIAIAMAAAAPACACAAARADADAAASACADAAAADwAgAgAAEQAwAwAAEgAgCgkAAPkCACAKAAD6AgAgCwAA-wIAIL0BAgAAAAHBAUAAAAAB2wECAAAAAdwBAQAAAAHdAQEAAAAB3gECAAAAAd8BAgAAAAEBFwAAuQEAIAe9AQIAAAABwQFAAAAAAdsBAgAAAAHcAQEAAAAB3QEBAAAAAd4BAgAAAAHfAQIAAAABARcAALsBADABFwAAuwEAMAoJAAD2AgAgCgAA9wIAIAsAAPgCACC9AQIA9QIAIcEBQADiAgAh2wECAPUCACHcAQEA5wIAId0BAQDhAgAh3gECAPUCACHfAQIA9QIAIQIAAAASACAXAAC-AQAgB70BAgD1AgAhwQFAAOICACHbAQIA9QIAIdwBAQDnAgAh3QEBAOECACHeAQIA9QIAId8BAgD1AgAhAgAAAA8AIBcAAMABACACAAAADwAgFwAAwAEAIAMAAAASACAeAAC5AQAgHwAAvgEAIAEAAAASACABAAAADwAgBgYAAPACACAkAADzAgAgJQAA8gIAIDYAAPECACA3AAD0AgAg3AEAAOMCACAKugEAAKMCADC7AQAAxwEAELwBAACjAgAwvQECAKQCACHBAUAAkQIAIdsBAgCkAgAh3AEBAJsCACHdAQEAkAIAId4BAgCkAgAh3wECAKQCACEDAAAADwAgAgAAxgEAMCMAAMcBACADAAAADwAgAgAAEQAwAwAAEgAgAQAAACAAIAEAAAAgACADAAAAHgAgAgAAHwAwAwAAIAAgAwAAAB4AIAIAAB8AMAMAACAAIAMAAAAeACACAAAfADADAAAgACAJAQAA7wIAIL0BAQAAAAHAAUAAAAABwQFAAAAAAcIBQAAAAAHQAQEAAAAB2AEBAAAAAdkBAQAAAAHaAQEAAAABARcAAM8BACAIvQEBAAAAAcABQAAAAAHBAUAAAAABwgFAAAAAAdABAQAAAAHYAQEAAAAB2QEBAAAAAdoBAQAAAAEBFwAA0QEAMAEXAADRAQAwCQEAAO4CACC9AQEA4QIAIcABQADiAgAhwQFAAOICACHCAUAA4gIAIdABAQDhAgAh2AEBAOECACHZAQEA5wIAIdoBAQDnAgAhAgAAACAAIBcAANQBACAIvQEBAOECACHAAUAA4gIAIcEBQADiAgAhwgFAAOICACHQAQEA4QIAIdgBAQDhAgAh2QEBAOcCACHaAQEA5wIAIQIAAAAeACAXAADWAQAgAgAAAB4AIBcAANYBACADAAAAIAAgHgAAzwEAIB8AANQBACABAAAAIAAgAQAAAB4AIAUGAADrAgAgJAAA7QIAICUAAOwCACDZAQAA4wIAINoBAADjAgAgC7oBAACiAgAwuwEAAN0BABC8AQAAogIAML0BAQCQAgAhwAFAAJECACHBAUAAkQIAIcIBQACRAgAh0AEBAJACACHYAQEAkAIAIdkBAQCbAgAh2gEBAJsCACEDAAAAHgAgAgAA3AEAMCMAAN0BACADAAAAHgAgAgAAHwAwAwAAIAAgAQAAACQAIAEAAAAkACADAAAAIgAgAgAAIwAwAwAAJAAgAwAAACIAIAIAACMAMAMAACQAIAMAAAAiACACAAAjADADAAAkACAOAQAA6gIAIL0BAQAAAAHBAUAAAAABwgFAAAAAAc4BAQAAAAHPAQEAAAAB0AEBAAAAAdEBAQAAAAHSAQEAAAAB0wEBAAAAAdQBAQAAAAHVAUAAAAAB1gFAAAAAAdcBAQAAAAEBFwAA5QEAIA29AQEAAAABwQFAAAAAAcIBQAAAAAHOAQEAAAABzwEBAAAAAdABAQAAAAHRAQEAAAAB0gEBAAAAAdMBAQAAAAHUAQEAAAAB1QFAAAAAAdYBQAAAAAHXAQEAAAABARcAAOcBADABFwAA5wEAMA4BAADpAgAgvQEBAOECACHBAUAA4gIAIcIBQADiAgAhzgEBAOECACHPAQEA4QIAIdABAQDhAgAh0QEBAOcCACHSAQEA5wIAIdMBAQDnAgAh1AEBAOcCACHVAUAA6AIAIdYBQADoAgAh1wEBAOcCACECAAAAJAAgFwAA6gEAIA29AQEA4QIAIcEBQADiAgAhwgFAAOICACHOAQEA4QIAIc8BAQDhAgAh0AEBAOECACHRAQEA5wIAIdIBAQDnAgAh0wEBAOcCACHUAQEA5wIAIdUBQADoAgAh1gFAAOgCACHXAQEA5wIAIQIAAAAiACAXAADsAQAgAgAAACIAIBcAAOwBACADAAAAJAAgHgAA5QEAIB8AAOoBACABAAAAJAAgAQAAACIAIAoGAADkAgAgJAAA5gIAICUAAOUCACDRAQAA4wIAINIBAADjAgAg0wEAAOMCACDUAQAA4wIAINUBAADjAgAg1gEAAOMCACDXAQAA4wIAIBC6AQAAmgIAMLsBAADzAQAQvAEAAJoCADC9AQEAkAIAIcEBQACRAgAhwgFAAJECACHOAQEAkAIAIc8BAQCQAgAh0AEBAJACACHRAQEAmwIAIdIBAQCbAgAh0wEBAJsCACHUAQEAmwIAIdUBQACcAgAh1gFAAJwCACHXAQEAmwIAIQMAAAAiACACAADyAQAwIwAA8wEAIAMAAAAiACACAAAjADADAAAkACAJugEAAJcCADC7AQAA-QEAELwBAACXAgAwvQEBAAAAAb4BAQCYAgAhvwEBAJgCACHAAUAAmQIAIcEBQACZAgAhwgFAAJkCACEBAAAA9gEAIAEAAAD2AQAgCboBAACXAgAwuwEAAPkBABC8AQAAlwIAML0BAQCYAgAhvgEBAJgCACG_AQEAmAIAIcABQACZAgAhwQFAAJkCACHCAUAAmQIAIQADAAAA-QEAIAIAAPoBADADAAD2AQAgAwAAAPkBACACAAD6AQAwAwAA9gEAIAMAAAD5AQAgAgAA-gEAMAMAAPYBACAGvQEBAAAAAb4BAQAAAAG_AQEAAAABwAFAAAAAAcEBQAAAAAHCAUAAAAABARcAAP4BACAGvQEBAAAAAb4BAQAAAAG_AQEAAAABwAFAAAAAAcEBQAAAAAHCAUAAAAABARcAAIACADABFwAAgAIAMAa9AQEA4QIAIb4BAQDhAgAhvwEBAOECACHAAUAA4gIAIcEBQADiAgAhwgFAAOICACECAAAA9gEAIBcAAIMCACAGvQEBAOECACG-AQEA4QIAIb8BAQDhAgAhwAFAAOICACHBAUAA4gIAIcIBQADiAgAhAgAAAPkBACAXAACFAgAgAgAAAPkBACAXAACFAgAgAwAAAPYBACAeAAD-AQAgHwAAgwIAIAEAAAD2AQAgAQAAAPkBACADBgAA3gIAICQAAOACACAlAADfAgAgCboBAACPAgAwuwEAAIwCABC8AQAAjwIAML0BAQCQAgAhvgEBAJACACG_AQEAkAIAIcABQACRAgAhwQFAAJECACHCAUAAkQIAIQMAAAD5AQAgAgAAiwIAMCMAAIwCACADAAAA-QEAIAIAAPoBADADAAD2AQAgCboBAACPAgAwuwEAAIwCABC8AQAAjwIAML0BAQCQAgAhvgEBAJACACG_AQEAkAIAIcABQACRAgAhwQFAAJECACHCAUAAkQIAIQ4GAACTAgAgJAAAlgIAICUAAJYCACDDAQEAAAABxAEBAAAABMUBAQAAAATGAQEAAAABxwEBAAAAAcgBAQAAAAHJAQEAAAABygEBAJUCACHLAQEAAAABzAEBAAAAAc0BAQAAAAELBgAAkwIAICQAAJQCACAlAACUAgAgwwFAAAAAAcQBQAAAAATFAUAAAAAExgFAAAAAAccBQAAAAAHIAUAAAAAByQFAAAAAAcoBQACSAgAhCwYAAJMCACAkAACUAgAgJQAAlAIAIMMBQAAAAAHEAUAAAAAExQFAAAAABMYBQAAAAAHHAUAAAAAByAFAAAAAAckBQAAAAAHKAUAAkgIAIQjDAQIAAAABxAECAAAABMUBAgAAAATGAQIAAAABxwECAAAAAcgBAgAAAAHJAQIAAAABygECAJMCACEIwwFAAAAAAcQBQAAAAATFAUAAAAAExgFAAAAAAccBQAAAAAHIAUAAAAAByQFAAAAAAcoBQACUAgAhDgYAAJMCACAkAACWAgAgJQAAlgIAIMMBAQAAAAHEAQEAAAAExQEBAAAABMYBAQAAAAHHAQEAAAAByAEBAAAAAckBAQAAAAHKAQEAlQIAIcsBAQAAAAHMAQEAAAABzQEBAAAAAQvDAQEAAAABxAEBAAAABMUBAQAAAATGAQEAAAABxwEBAAAAAcgBAQAAAAHJAQEAAAABygEBAJYCACHLAQEAAAABzAEBAAAAAc0BAQAAAAEJugEAAJcCADC7AQAA-QEAELwBAACXAgAwvQEBAJgCACG-AQEAmAIAIb8BAQCYAgAhwAFAAJkCACHBAUAAmQIAIcIBQACZAgAhC8MBAQAAAAHEAQEAAAAExQEBAAAABMYBAQAAAAHHAQEAAAAByAEBAAAAAckBAQAAAAHKAQEAlgIAIcsBAQAAAAHMAQEAAAABzQEBAAAAAQjDAUAAAAABxAFAAAAABMUBQAAAAATGAUAAAAABxwFAAAAAAcgBQAAAAAHJAUAAAAABygFAAJQCACEQugEAAJoCADC7AQAA8wEAELwBAACaAgAwvQEBAJACACHBAUAAkQIAIcIBQACRAgAhzgEBAJACACHPAQEAkAIAIdABAQCQAgAh0QEBAJsCACHSAQEAmwIAIdMBAQCbAgAh1AEBAJsCACHVAUAAnAIAIdYBQACcAgAh1wEBAJsCACEOBgAAngIAICQAAKECACAlAAChAgAgwwEBAAAAAcQBAQAAAAXFAQEAAAAFxgEBAAAAAccBAQAAAAHIAQEAAAAByQEBAAAAAcoBAQCgAgAhywEBAAAAAcwBAQAAAAHNAQEAAAABCwYAAJ4CACAkAACfAgAgJQAAnwIAIMMBQAAAAAHEAUAAAAAFxQFAAAAABcYBQAAAAAHHAUAAAAAByAFAAAAAAckBQAAAAAHKAUAAnQIAIQsGAACeAgAgJAAAnwIAICUAAJ8CACDDAUAAAAABxAFAAAAABcUBQAAAAAXGAUAAAAABxwFAAAAAAcgBQAAAAAHJAUAAAAABygFAAJ0CACEIwwECAAAAAcQBAgAAAAXFAQIAAAAFxgECAAAAAccBAgAAAAHIAQIAAAAByQECAAAAAcoBAgCeAgAhCMMBQAAAAAHEAUAAAAAFxQFAAAAABcYBQAAAAAHHAUAAAAAByAFAAAAAAckBQAAAAAHKAUAAnwIAIQ4GAACeAgAgJAAAoQIAICUAAKECACDDAQEAAAABxAEBAAAABcUBAQAAAAXGAQEAAAABxwEBAAAAAcgBAQAAAAHJAQEAAAABygEBAKACACHLAQEAAAABzAEBAAAAAc0BAQAAAAELwwEBAAAAAcQBAQAAAAXFAQEAAAAFxgEBAAAAAccBAQAAAAHIAQEAAAAByQEBAAAAAcoBAQChAgAhywEBAAAAAcwBAQAAAAHNAQEAAAABC7oBAACiAgAwuwEAAN0BABC8AQAAogIAML0BAQCQAgAhwAFAAJECACHBAUAAkQIAIcIBQACRAgAh0AEBAJACACHYAQEAkAIAIdkBAQCbAgAh2gEBAJsCACEKugEAAKMCADC7AQAAxwEAELwBAACjAgAwvQECAKQCACHBAUAAkQIAIdsBAgCkAgAh3AEBAJsCACHdAQEAkAIAId4BAgCkAgAh3wECAKQCACENBgAAkwIAICQAAJMCACAlAACTAgAgNgAApgIAIDcAAJMCACDDAQIAAAABxAECAAAABMUBAgAAAATGAQIAAAABxwECAAAAAcgBAgAAAAHJAQIAAAABygECAKUCACENBgAAkwIAICQAAJMCACAlAACTAgAgNgAApgIAIDcAAJMCACDDAQIAAAABxAECAAAABMUBAgAAAATGAQIAAAABxwECAAAAAcgBAgAAAAHJAQIAAAABygECAKUCACEIwwEIAAAAAcQBCAAAAATFAQgAAAAExgEIAAAAAccBCAAAAAHIAQgAAAAByQEIAAAAAcoBCACmAgAhCboBAACnAgAwuwEAALEBABC8AQAApwIAML0BAgCkAgAhwQFAAJECACHdAQEAkAIAId4BAgCkAgAh4AFAAJECACHiAQAAqALiASIHBgAAkwIAICQAAKoCACAlAACqAgAgwwEAAADiAQLEAQAAAOIBCMUBAAAA4gEIygEAAKkC4gEiBwYAAJMCACAkAACqAgAgJQAAqgIAIMMBAAAA4gECxAEAAADiAQjFAQAAAOIBCMoBAACpAuIBIgTDAQAAAOIBAsQBAAAA4gEIxQEAAADiAQjKAQAAqgLiASIJugEAAKsCADC7AQAAmwEAELwBAACrAgAwvQECAKQCACHBAUAAkQIAId4BAgCkAgAh4wECAKQCACHkAQEAkAIAIeUBAQCQAgAhBboBAACsAgAwuwEAAIUBABC8AQAArAIAMOYBAgCkAgAh5wECAKQCACEFugEAAK0CADC7AQAAbwAQvAEAAK0CADC9AQIApAIAIegBAQCQAgAhBgUAALACACC6AQAArgIAMLsBAABcABC8AQAArgIAML0BAgCvAgAh6AEBAJgCACEIwwECAAAAAcQBAgAAAATFAQIAAAAExgECAAAAAccBAgAAAAHIAQIAAAAByQECAAAAAcoBAgCTAgAhA-kBAAAFACDqAQAABQAg6wEAAAUAIAq6AQAAsQIAMLsBAABWABC8AQAAsQIAML0BAgCkAgAhwQFAAJECACHCAUAAkQIAIdABAQCQAgAh4gEAALMC7wEi7AEBAJACACHtAQgAsgIAIQ0GAACTAgAgJAAApgIAICUAAKYCACA2AACmAgAgNwAApgIAIMMBCAAAAAHEAQgAAAAExQEIAAAABMYBCAAAAAHHAQgAAAAByAEIAAAAAckBCAAAAAHKAQgAtgIAIQcGAACTAgAgJAAAtQIAICUAALUCACDDAQAAAO8BAsQBAAAA7wEIxQEAAADvAQjKAQAAtALvASIHBgAAkwIAICQAALUCACAlAAC1AgAgwwEAAADvAQLEAQAAAO8BCMUBAAAA7wEIygEAALQC7wEiBMMBAAAA7wECxAEAAADvAQjFAQAAAO8BCMoBAAC1Au8BIg0GAACTAgAgJAAApgIAICUAAKYCACA2AACmAgAgNwAApgIAIMMBCAAAAAHEAQgAAAAExQEIAAAABMYBCAAAAAHHAQgAAAAByAEIAAAAAckBCAAAAAHKAQgAtgIAIQ8BAAC6AgAgCAAAsAIAIA0AALsCACAOAAC8AgAgDwAAvQIAILoBAAC3AgAwuwEAAAMAELwBAAC3AgAwvQECAK8CACHBAUAAmQIAIcIBQACZAgAh0AEBAJgCACHiAQAAuQLvASLsAQEAmAIAIe0BCAC4AgAhCMMBCAAAAAHEAQgAAAAExQEIAAAABMYBCAAAAAHHAQgAAAAByAEIAAAAAckBCAAAAAHKAQgApgIAIQTDAQAAAO8BAsQBAAAA7wEIxQEAAADvAQjKAQAAtQLvASITBAAAzQIAIA0AALsCACAOAAC8AgAgEAAAzgIAIBEAAM8CACC6AQAAyAIAMLsBAAArABC8AQAAyAIAML0BAQCYAgAhwQFAAJkCACHCAUAAmQIAIeIBAADLAvQBIugBAQDJAgAh7wEBAJgCACHxAQAAygLxASLyAQEAyQIAIfQBIADMAgAh9wEAACsAIPgBAAArACAD6QEAAAsAIOoBAAALACDrAQAACwAgA-kBAAAPACDqAQAADwAg6wEAAA8AIAPpAQAAFAAg6gEAABQAIOsBAAAUACAMugEAAL4CADC7AQAAPgAQvAEAAL4CADC9AQEAkAIAIcEBQACRAgAhwgFAAJECACHiAQAAwAL0ASLoAQEAmwIAIe8BAQCQAgAh8QEAAL8C8QEi8gEBAJsCACH0ASAAwQIAIQcGAACTAgAgJAAAxwIAICUAAMcCACDDAQAAAPEBAsQBAAAA8QEIxQEAAADxAQjKAQAAxgLxASIHBgAAkwIAICQAAMUCACAlAADFAgAgwwEAAAD0AQLEAQAAAPQBCMUBAAAA9AEIygEAAMQC9AEiBQYAAJMCACAkAADDAgAgJQAAwwIAIMMBIAAAAAHKASAAwgIAIQUGAACTAgAgJAAAwwIAICUAAMMCACDDASAAAAABygEgAMICACECwwEgAAAAAcoBIADDAgAhBwYAAJMCACAkAADFAgAgJQAAxQIAIMMBAAAA9AECxAEAAAD0AQjFAQAAAPQBCMoBAADEAvQBIgTDAQAAAPQBAsQBAAAA9AEIxQEAAAD0AQjKAQAAxQL0ASIHBgAAkwIAICQAAMcCACAlAADHAgAgwwEAAADxAQLEAQAAAPEBCMUBAAAA8QEIygEAAMYC8QEiBMMBAAAA8QECxAEAAADxAQjFAQAAAPEBCMoBAADHAvEBIhEEAADNAgAgDQAAuwIAIA4AALwCACAQAADOAgAgEQAAzwIAILoBAADIAgAwuwEAACsAELwBAADIAgAwvQEBAJgCACHBAUAAmQIAIcIBQACZAgAh4gEAAMsC9AEi6AEBAMkCACHvAQEAmAIAIfEBAADKAvEBIvIBAQDJAgAh9AEgAMwCACELwwEBAAAAAcQBAQAAAAXFAQEAAAAFxgEBAAAAAccBAQAAAAHIAQEAAAAByQEBAAAAAcoBAQChAgAhywEBAAAAAcwBAQAAAAHNAQEAAAABBMMBAAAA8QECxAEAAADxAQjFAQAAAPEBCMoBAADHAvEBIgTDAQAAAPQBAsQBAAAA9AEIxQEAAAD0AQjKAQAAxQL0ASICwwEgAAAAAcoBIADDAgAhEQEAALoCACAIAACwAgAgDQAAuwIAIA4AALwCACAPAAC9AgAgugEAALcCADC7AQAAAwAQvAEAALcCADC9AQIArwIAIcEBQACZAgAhwgFAAJkCACHQAQEAmAIAIeIBAAC5Au8BIuwBAQCYAgAh7QEIALgCACH3AQAAAwAg-AEAAAMAIAPpAQAAHgAg6gEAAB4AIOsBAAAeACAD6QEAACIAIOoBAAAiACDrAQAAIgAgEQEAALoCACC6AQAA0AIAMLsBAAAiABC8AQAA0AIAML0BAQCYAgAhwQFAAJkCACHCAUAAmQIAIc4BAQCYAgAhzwEBAJgCACHQAQEAmAIAIdEBAQDJAgAh0gEBAMkCACHTAQEAyQIAIdQBAQDJAgAh1QFAANECACHWAUAA0QIAIdcBAQDJAgAhCMMBQAAAAAHEAUAAAAAFxQFAAAAABcYBQAAAAAHHAUAAAAAByAFAAAAAAckBQAAAAAHKAUAAnwIAIQwBAAC6AgAgugEAANICADC7AQAAHgAQvAEAANICADC9AQEAmAIAIcABQACZAgAhwQFAAJkCACHCAUAAmQIAIdABAQCYAgAh2AEBAJgCACHZAQEAyQIAIdoBAQDJAgAhAt4BAgAAAAHjAQIAAAABCgoAANUCACC6AQAA1AIAMLsBAAAUABC8AQAA1AIAML0BAgCvAgAhwQFAAJkCACHeAQIArwIAIeMBAgCvAgAh5AEBAJgCACHlAQEAmAIAIREBAAC6AgAgCAAAsAIAIA0AALsCACAOAAC8AgAgDwAAvQIAILoBAAC3AgAwuwEAAAMAELwBAAC3AgAwvQECAK8CACHBAUAAmQIAIcIBQACZAgAh0AEBAJgCACHiAQAAuQLvASLsAQEAmAIAIe0BCAC4AgAh9wEAAAMAIPgBAAADACANCQAAugIAIAoAANUCACALAADXAgAgugEAANYCADC7AQAADwAQvAEAANYCADC9AQIArwIAIcEBQACZAgAh2wECAK8CACHcAQEAyQIAId0BAQCYAgAh3gECAK8CACHfAQIArwIAIQ4JAAC6AgAgCgAA1QIAIAwAANoCACC6AQAA2AIAMLsBAAALABC8AQAA2AIAML0BAgCvAgAhwQFAAJkCACHdAQEAmAIAId4BAgCvAgAh4AFAAJkCACHiAQAA2QLiASL3AQAACwAg-AEAAAsAIAwJAAC6AgAgCgAA1QIAIAwAANoCACC6AQAA2AIAMLsBAAALABC8AQAA2AIAML0BAgCvAgAhwQFAAJkCACHdAQEAmAIAId4BAgCvAgAh4AFAAJkCACHiAQAA2QLiASIEwwEAAADiAQLEAQAAAOIBCMUBAAAA4gEIygEAAKoC4gEiDwkAALoCACAKAADVAgAgCwAA1wIAILoBAADWAgAwuwEAAA8AELwBAADWAgAwvQECAK8CACHBAUAAmQIAIdsBAgCvAgAh3AEBAMkCACHdAQEAmAIAId4BAgCvAgAh3wECAK8CACH3AQAADwAg-AEAAA8AIALmAQIAAAAB5wECAAAAAQcEAADVAgAgBwAA3QIAILoBAADcAgAwuwEAAAUAELwBAADcAgAw5gECAK8CACHnAQIArwIAIQgFAACwAgAgugEAAK4CADC7AQAAXAAQvAEAAK4CADC9AQIArwIAIegBAQCYAgAh9wEAAFwAIPgBAABcACAAAAAB_wEBAAAAAQH_AUAAAAABAAAAAAH_AQEAAAABAf8BQAAAAAEFHgAA8wQAIB8AAPYEACD5AQAA9AQAIPoBAAD1BAAg_QEAAAEAIAMeAADzBAAg-QEAAPQEACD9AQAAAQAgAAAABR4AAO4EACAfAADxBAAg-QEAAO8EACD6AQAA8AQAIP0BAAABACADHgAA7gQAIPkBAADvBAAg_QEAAAEAIAAAAAAABf8BAgAAAAGCAgIAAAABgwICAAAAAYQCAgAAAAGFAgIAAAABBR4AAOMEACAfAADsBAAg-QEAAOQEACD6AQAA6wQAIP0BAAABACAFHgAA4QQAIB8AAOkEACD5AQAA4gQAIPoBAADoBAAg_QEAAEEAIAUeAADfBAAgHwAA5gQAIPkBAADgBAAg-gEAAOUEACD9AQAADQAgAx4AAOMEACD5AQAA5AQAIP0BAAABACADHgAA4QQAIPkBAADiBAAg_QEAAEEAIAMeAADfBAAg-QEAAOAEACD9AQAADQAgAAAAAAAB_wEAAADiAQIFHgAA1wQAIB8AAN0EACD5AQAA2AQAIPoBAADcBAAg_QEAAAEAIAUeAADVBAAgHwAA2gQAIPkBAADWBAAg-gEAANkEACD9AQAAQQAgBx4AAIUDACAfAACIAwAg-QEAAIYDACD6AQAAhwMAIPsBAAAPACD8AQAADwAg_QEAABIAIAgJAAD5AgAgCgAA-gIAIL0BAgAAAAHBAUAAAAAB2wECAAAAAdwBAQAAAAHdAQEAAAAB3gECAAAAAQIAAAASACAeAACFAwAgAwAAAA8AIB4AAIUDACAfAACJAwAgCgAAAA8AIAkAAPYCACAKAAD3AgAgFwAAiQMAIL0BAgD1AgAhwQFAAOICACHbAQIA9QIAIdwBAQDnAgAh3QEBAOECACHeAQIA9QIAIQgJAAD2AgAgCgAA9wIAIL0BAgD1AgAhwQFAAOICACHbAQIA9QIAIdwBAQDnAgAh3QEBAOECACHeAQIA9QIAIQMeAADXBAAg-QEAANgEACD9AQAAAQAgAx4AANUEACD5AQAA1gQAIP0BAABBACADHgAAhQMAIPkBAACGAwAg_QEAABIAIAAAAAAABR4AANAEACAfAADTBAAg-QEAANEEACD6AQAA0gQAIP0BAABBACADHgAA0AQAIPkBAADRBAAg_QEAAEEAIAAAAAAABR4AAMgEACAfAADOBAAg-QEAAMkEACD6AQAAzQQAIP0BAABBACAFHgAAxgQAIB8AAMsEACD5AQAAxwQAIPoBAADKBAAg_QEAAFkAIAMeAADIBAAg-QEAAMkEACD9AQAAQQAgAx4AAMYEACD5AQAAxwQAIP0BAABZACAAAAAAAAseAACjAwAwHwAAqAMAMPkBAACkAwAw-gEAAKUDADD7AQAApwMAMPwBAACnAwAw_QEAAKcDADD-AQAApgMAIP8BAACnAwAwgAIAAKkDADCBAgAAqgMAMAIEAACbAwAg5gECAAAAAQIAAAAHACAeAACuAwAgAwAAAAcAIB4AAK4DACAfAACtAwAgARcAAMUEADAIBAAA1QIAIAcAAN0CACC6AQAA3AIAMLsBAAAFABC8AQAA3AIAMOYBAgCvAgAh5wECAK8CACH2AQAA2wIAIAIAAAAHACAXAACtAwAgAgAAAKsDACAXAACsAwAgBboBAACqAwAwuwEAAKsDABC8AQAAqgMAMOYBAgCvAgAh5wECAK8CACEFugEAAKoDADC7AQAAqwMAELwBAACqAwAw5gECAK8CACHnAQIArwIAIQHmAQIA9QIAIQIEAACZAwAg5gECAPUCACECBAAAmwMAIOYBAgAAAAEEHgAAowMAMPkBAACkAwAw_QEAAKcDADD-AQAApgMAIAAAAAAAAAX_AQgAAAABggIIAAAAAYMCCAAAAAGEAggAAAABhQIIAAAAAQH_AQAAAO8BAgUeAAC8BAAgHwAAwwQAIPkBAAC9BAAg-gEAAMIEACD9AQAAAQAgCx4AAOEDADAfAADlAwAw-QEAAOIDADD6AQAA4wMAMPsBAACnAwAw_AEAAKcDADD9AQAApwMAMP4BAADkAwAg_wEAAKcDADCAAgAA5gMAMIECAACqAwAwCx4AANUDADAfAADaAwAw-QEAANYDADD6AQAA1wMAMPsBAADZAwAw_AEAANkDADD9AQAA2QMAMP4BAADYAwAg_wEAANkDADCAAgAA2wMAMIECAADcAwAwCx4AAMkDADAfAADOAwAw-QEAAMoDADD6AQAAywMAMPsBAADNAwAw_AEAAM0DADD9AQAAzQMAMP4BAADMAwAg_wEAAM0DADCAAgAAzwMAMIECAADQAwAwCx4AAL0DADAfAADCAwAw-QEAAL4DADD6AQAAvwMAMPsBAADBAwAw_AEAAMEDADD9AQAAwQMAMP4BAADAAwAg_wEAAMEDADCAAgAAwwMAMIECAADEAwAwBb0BAgAAAAHBAUAAAAAB4wECAAAAAeQBAQAAAAHlAQEAAAABAgAAABYAIB4AAMgDACADAAAAFgAgHgAAyAMAIB8AAMcDACABFwAAwQQAMAsKAADVAgAgugEAANQCADC7AQAAFAAQvAEAANQCADC9AQIAAAABwQFAAJkCACHeAQIArwIAIeMBAgCvAgAh5AEBAJgCACHlAQEAmAIAIfUBAADTAgAgAgAAABYAIBcAAMcDACACAAAAxQMAIBcAAMYDACAJugEAAMQDADC7AQAAxQMAELwBAADEAwAwvQECAK8CACHBAUAAmQIAId4BAgCvAgAh4wECAK8CACHkAQEAmAIAIeUBAQCYAgAhCboBAADEAwAwuwEAAMUDABC8AQAAxAMAML0BAgCvAgAhwQFAAJkCACHeAQIArwIAIeMBAgCvAgAh5AEBAJgCACHlAQEAmAIAIQW9AQIA9QIAIcEBQADiAgAh4wECAPUCACHkAQEA4QIAIeUBAQDhAgAhBb0BAgD1AgAhwQFAAOICACHjAQIA9QIAIeQBAQDhAgAh5QEBAOECACEFvQECAAAAAcEBQAAAAAHjAQIAAAAB5AEBAAAAAeUBAQAAAAEICQAA-QIAIAsAAPsCACC9AQIAAAABwQFAAAAAAdsBAgAAAAHcAQEAAAAB3QEBAAAAAd8BAgAAAAECAAAAEgAgHgAA1AMAIAMAAAASACAeAADUAwAgHwAA0wMAIAEXAADABAAwDQkAALoCACAKAADVAgAgCwAA1wIAILoBAADWAgAwuwEAAA8AELwBAADWAgAwvQECAAAAAcEBQACZAgAh2wECAK8CACHcAQEAyQIAId0BAQCYAgAh3gECAK8CACHfAQIAAAABAgAAABIAIBcAANMDACACAAAA0QMAIBcAANIDACAKugEAANADADC7AQAA0QMAELwBAADQAwAwvQECAK8CACHBAUAAmQIAIdsBAgCvAgAh3AEBAMkCACHdAQEAmAIAId4BAgCvAgAh3wECAK8CACEKugEAANADADC7AQAA0QMAELwBAADQAwAwvQECAK8CACHBAUAAmQIAIdsBAgCvAgAh3AEBAMkCACHdAQEAmAIAId4BAgCvAgAh3wECAK8CACEGvQECAPUCACHBAUAA4gIAIdsBAgD1AgAh3AEBAOcCACHdAQEA4QIAId8BAgD1AgAhCAkAAPYCACALAAD4AgAgvQECAPUCACHBAUAA4gIAIdsBAgD1AgAh3AEBAOcCACHdAQEA4QIAId8BAgD1AgAhCAkAAPkCACALAAD7AgAgvQECAAAAAcEBQAAAAAHbAQIAAAAB3AEBAAAAAd0BAQAAAAHfAQIAAAABBwkAAIoDACAMAACMAwAgvQECAAAAAcEBQAAAAAHdAQEAAAAB4AFAAAAAAeIBAAAA4gECAgAAAA0AIB4AAOADACADAAAADQAgHgAA4AMAIB8AAN8DACABFwAAvwQAMAwJAAC6AgAgCgAA1QIAIAwAANoCACC6AQAA2AIAMLsBAAALABC8AQAA2AIAML0BAgAAAAHBAUAAmQIAId0BAQCYAgAh3gECAK8CACHgAUAAmQIAIeIBAADZAuIBIgIAAAANACAXAADfAwAgAgAAAN0DACAXAADeAwAgCboBAADcAwAwuwEAAN0DABC8AQAA3AMAML0BAgCvAgAhwQFAAJkCACHdAQEAmAIAId4BAgCvAgAh4AFAAJkCACHiAQAA2QLiASIJugEAANwDADC7AQAA3QMAELwBAADcAwAwvQECAK8CACHBAUAAmQIAId0BAQCYAgAh3gECAK8CACHgAUAAmQIAIeIBAADZAuIBIgW9AQIA9QIAIcEBQADiAgAh3QEBAOECACHgAUAA4gIAIeIBAACBA-IBIgcJAACCAwAgDAAAhAMAIL0BAgD1AgAhwQFAAOICACHdAQEA4QIAIeABQADiAgAh4gEAAIED4gEiBwkAAIoDACAMAACMAwAgvQECAAAAAcEBQAAAAAHdAQEAAAAB4AFAAAAAAeIBAAAA4gECAgcAAJwDACDnAQIAAAABAgAAAAcAIB4AAOkDACADAAAABwAgHgAA6QMAIB8AAOgDACABFwAAvgQAMAIAAAAHACAXAADoAwAgAgAAAKsDACAXAADnAwAgAecBAgD1AgAhAgcAAJoDACDnAQIA9QIAIQIHAACcAwAg5wECAAAAAQMeAAC8BAAg-QEAAL0EACD9AQAAAQAgBB4AAOEDADD5AQAA4gMAMP0BAACnAwAw_gEAAOQDACAEHgAA1QMAMPkBAADWAwAw_QEAANkDADD-AQAA2AMAIAQeAADJAwAw-QEAAMoDADD9AQAAzQMAMP4BAADMAwAgBB4AAL0DADD5AQAAvgMAMP0BAADBAwAw_gEAAMADACAHBAAAsgQAIA0AAPADACAOAADxAwAgEAAAswQAIBEAALQEACDoAQAA4wIAIPIBAADjAgAgAAAAAAAAAf8BAAAA8QECAf8BAAAA9AECAf8BIAAAAAEHHgAAqAQAIB8AAKsEACD5AQAAqQQAIPoBAACqBAAg-wEAAAMAIPwBAAADACD9AQAAQQAgCx4AAJ8EADAfAACjBAAw-QEAAKAEADD6AQAAoQQAMPsBAADZAwAw_AEAANkDADD9AQAA2QMAMP4BAACiBAAg_wEAANkDADCAAgAApAQAMIECAADcAwAwCx4AAJYEADAfAACaBAAw-QEAAJcEADD6AQAAmAQAMPsBAADNAwAw_AEAAM0DADD9AQAAzQMAMP4BAACZBAAg_wEAAM0DADCAAgAAmwQAMIECAADQAwAwCx4AAIoEADAfAACPBAAw-QEAAIsEADD6AQAAjAQAMPsBAACOBAAw_AEAAI4EADD9AQAAjgQAMP4BAACNBAAg_wEAAI4EADCAAgAAkAQAMIECAACRBAAwCx4AAP4DADAfAACDBAAw-QEAAP8DADD6AQAAgAQAMPsBAACCBAAw_AEAAIIEADD9AQAAggQAMP4BAACBBAAg_wEAAIIEADCAAgAAhAQAMIECAACFBAAwDL0BAQAAAAHBAUAAAAABwgFAAAAAAc4BAQAAAAHPAQEAAAAB0QEBAAAAAdIBAQAAAAHTAQEAAAAB1AEBAAAAAdUBQAAAAAHWAUAAAAAB1wEBAAAAAQIAAAAkACAeAACJBAAgAwAAACQAIB4AAIkEACAfAACIBAAgARcAALsEADARAQAAugIAILoBAADQAgAwuwEAACIAELwBAADQAgAwvQEBAAAAAcEBQACZAgAhwgFAAJkCACHOAQEAmAIAIc8BAQCYAgAh0AEBAJgCACHRAQEAyQIAIdIBAQDJAgAh0wEBAMkCACHUAQEAyQIAIdUBQADRAgAh1gFAANECACHXAQEAyQIAIQIAAAAkACAXAACIBAAgAgAAAIYEACAXAACHBAAgELoBAACFBAAwuwEAAIYEABC8AQAAhQQAML0BAQCYAgAhwQFAAJkCACHCAUAAmQIAIc4BAQCYAgAhzwEBAJgCACHQAQEAmAIAIdEBAQDJAgAh0gEBAMkCACHTAQEAyQIAIdQBAQDJAgAh1QFAANECACHWAUAA0QIAIdcBAQDJAgAhELoBAACFBAAwuwEAAIYEABC8AQAAhQQAML0BAQCYAgAhwQFAAJkCACHCAUAAmQIAIc4BAQCYAgAhzwEBAJgCACHQAQEAmAIAIdEBAQDJAgAh0gEBAMkCACHTAQEAyQIAIdQBAQDJAgAh1QFAANECACHWAUAA0QIAIdcBAQDJAgAhDL0BAQDhAgAhwQFAAOICACHCAUAA4gIAIc4BAQDhAgAhzwEBAOECACHRAQEA5wIAIdIBAQDnAgAh0wEBAOcCACHUAQEA5wIAIdUBQADoAgAh1gFAAOgCACHXAQEA5wIAIQy9AQEA4QIAIcEBQADiAgAhwgFAAOICACHOAQEA4QIAIc8BAQDhAgAh0QEBAOcCACHSAQEA5wIAIdMBAQDnAgAh1AEBAOcCACHVAUAA6AIAIdYBQADoAgAh1wEBAOcCACEMvQEBAAAAAcEBQAAAAAHCAUAAAAABzgEBAAAAAc8BAQAAAAHRAQEAAAAB0gEBAAAAAdMBAQAAAAHUAQEAAAAB1QFAAAAAAdYBQAAAAAHXAQEAAAABB70BAQAAAAHAAUAAAAABwQFAAAAAAcIBQAAAAAHYAQEAAAAB2QEBAAAAAdoBAQAAAAECAAAAIAAgHgAAlQQAIAMAAAAgACAeAACVBAAgHwAAlAQAIAEXAAC6BAAwDAEAALoCACC6AQAA0gIAMLsBAAAeABC8AQAA0gIAML0BAQAAAAHAAUAAmQIAIcEBQACZAgAhwgFAAJkCACHQAQEAmAIAIdgBAQAAAAHZAQEAyQIAIdoBAQDJAgAhAgAAACAAIBcAAJQEACACAAAAkgQAIBcAAJMEACALugEAAJEEADC7AQAAkgQAELwBAACRBAAwvQEBAJgCACHAAUAAmQIAIcEBQACZAgAhwgFAAJkCACHQAQEAmAIAIdgBAQCYAgAh2QEBAMkCACHaAQEAyQIAIQu6AQAAkQQAMLsBAACSBAAQvAEAAJEEADC9AQEAmAIAIcABQACZAgAhwQFAAJkCACHCAUAAmQIAIdABAQCYAgAh2AEBAJgCACHZAQEAyQIAIdoBAQDJAgAhB70BAQDhAgAhwAFAAOICACHBAUAA4gIAIcIBQADiAgAh2AEBAOECACHZAQEA5wIAIdoBAQDnAgAhB70BAQDhAgAhwAFAAOICACHBAUAA4gIAIcIBQADiAgAh2AEBAOECACHZAQEA5wIAIdoBAQDnAgAhB70BAQAAAAHAAUAAAAABwQFAAAAAAcIBQAAAAAHYAQEAAAAB2QEBAAAAAdoBAQAAAAEICgAA-gIAIAsAAPsCACC9AQIAAAABwQFAAAAAAdsBAgAAAAHcAQEAAAAB3gECAAAAAd8BAgAAAAECAAAAEgAgHgAAngQAIAMAAAASACAeAACeBAAgHwAAnQQAIAEXAAC5BAAwAgAAABIAIBcAAJ0EACACAAAA0QMAIBcAAJwEACAGvQECAPUCACHBAUAA4gIAIdsBAgD1AgAh3AEBAOcCACHeAQIA9QIAId8BAgD1AgAhCAoAAPcCACALAAD4AgAgvQECAPUCACHBAUAA4gIAIdsBAgD1AgAh3AEBAOcCACHeAQIA9QIAId8BAgD1AgAhCAoAAPoCACALAAD7AgAgvQECAAAAAcEBQAAAAAHbAQIAAAAB3AEBAAAAAd4BAgAAAAHfAQIAAAABBwoAAIsDACAMAACMAwAgvQECAAAAAcEBQAAAAAHeAQIAAAAB4AFAAAAAAeIBAAAA4gECAgAAAA0AIB4AAKcEACADAAAADQAgHgAApwQAIB8AAKYEACABFwAAuAQAMAIAAAANACAXAACmBAAgAgAAAN0DACAXAAClBAAgBb0BAgD1AgAhwQFAAOICACHeAQIA9QIAIeABQADiAgAh4gEAAIED4gEiBwoAAIMDACAMAACEAwAgvQECAPUCACHBAUAA4gIAId4BAgD1AgAh4AFAAOICACHiAQAAgQPiASIHCgAAiwMAIAwAAIwDACC9AQIAAAABwQFAAAAAAd4BAgAAAAHgAUAAAAAB4gEAAADiAQIKCAAA6wMAIA0AAOwDACAOAADtAwAgDwAA7gMAIL0BAgAAAAHBAUAAAAABwgFAAAAAAeIBAAAA7wEC7AEBAAAAAe0BCAAAAAECAAAAQQAgHgAAqAQAIAMAAAADACAeAACoBAAgHwAArAQAIAwAAAADACAIAAC5AwAgDQAAugMAIA4AALsDACAPAAC8AwAgFwAArAQAIL0BAgD1AgAhwQFAAOICACHCAUAA4gIAIeIBAAC3A-8BIuwBAQDhAgAh7QEIALYDACEKCAAAuQMAIA0AALoDACAOAAC7AwAgDwAAvAMAIL0BAgD1AgAhwQFAAOICACHCAUAA4gIAIeIBAAC3A-8BIuwBAQDhAgAh7QEIALYDACEDHgAAqAQAIPkBAACpBAAg_QEAAEEAIAQeAACfBAAw-QEAAKAEADD9AQAA2QMAMP4BAACiBAAgBB4AAJYEADD5AQAAlwQAMP0BAADNAwAw_gEAAJkEACAEHgAAigQAMPkBAACLBAAw_QEAAI4EADD-AQAAjQQAIAQeAAD-AwAw-QEAAP8DADD9AQAAggQAMP4BAACBBAAgBQEAAO8DACAIAACwAwAgDQAA8AMAIA4AAPEDACAPAADyAwAgAAADCQAA7wMAIAoAALIEACAMAAC2BAAgBAkAAO8DACAKAACyBAAgCwAAtQQAINwBAADjAgAgAQUAALADACAFvQECAAAAAcEBQAAAAAHeAQIAAAAB4AFAAAAAAeIBAAAA4gECBr0BAgAAAAHBAUAAAAAB2wECAAAAAdwBAQAAAAHeAQIAAAAB3wECAAAAAQe9AQEAAAABwAFAAAAAAcEBQAAAAAHCAUAAAAAB2AEBAAAAAdkBAQAAAAHaAQEAAAABDL0BAQAAAAHBAUAAAAABwgFAAAAAAc4BAQAAAAHPAQEAAAAB0QEBAAAAAdIBAQAAAAHTAQEAAAAB1AEBAAAAAdUBQAAAAAHWAUAAAAAB1wEBAAAAAQ0NAACuBAAgDgAArwQAIBAAALAEACARAACxBAAgvQEBAAAAAcEBQAAAAAHCAUAAAAAB4gEAAAD0AQLoAQEAAAAB7wEBAAAAAfEBAAAA8QEC8gEBAAAAAfQBIAAAAAECAAAAAQAgHgAAvAQAIAHnAQIAAAABBb0BAgAAAAHBAUAAAAAB3QEBAAAAAeABQAAAAAHiAQAAAOIBAga9AQIAAAABwQFAAAAAAdsBAgAAAAHcAQEAAAAB3QEBAAAAAd8BAgAAAAEFvQECAAAAAcEBQAAAAAHjAQIAAAAB5AEBAAAAAeUBAQAAAAEDAAAAKwAgHgAAvAQAIB8AAMQEACAPAAAAKwAgDQAA-gMAIA4AAPsDACAQAAD8AwAgEQAA_QMAIBcAAMQEACC9AQEA4QIAIcEBQADiAgAhwgFAAOICACHiAQAA9wP0ASLoAQEA5wIAIe8BAQDhAgAh8QEAAPYD8QEi8gEBAOcCACH0ASAA-AMAIQ0NAAD6AwAgDgAA-wMAIBAAAPwDACARAAD9AwAgvQEBAOECACHBAUAA4gIAIcIBQADiAgAh4gEAAPcD9AEi6AEBAOcCACHvAQEA4QIAIfEBAAD2A_EBIvIBAQDnAgAh9AEgAPgDACEB5gECAAAAAQK9AQIAAAAB6AEBAAAAAQIAAABZACAeAADGBAAgCwEAAOoDACANAADsAwAgDgAA7QMAIA8AAO4DACC9AQIAAAABwQFAAAAAAcIBQAAAAAHQAQEAAAAB4gEAAADvAQLsAQEAAAAB7QEIAAAAAQIAAABBACAeAADIBAAgAwAAAFwAIB4AAMYEACAfAADMBAAgBAAAAFwAIBcAAMwEACC9AQIA9QIAIegBAQDhAgAhAr0BAgD1AgAh6AEBAOECACEDAAAAAwAgHgAAyAQAIB8AAM8EACANAAAAAwAgAQAAuAMAIA0AALoDACAOAAC7AwAgDwAAvAMAIBcAAM8EACC9AQIA9QIAIcEBQADiAgAhwgFAAOICACHQAQEA4QIAIeIBAAC3A-8BIuwBAQDhAgAh7QEIALYDACELAQAAuAMAIA0AALoDACAOAAC7AwAgDwAAvAMAIL0BAgD1AgAhwQFAAOICACHCAUAA4gIAIdABAQDhAgAh4gEAALcD7wEi7AEBAOECACHtAQgAtgMAIQsBAADqAwAgCAAA6wMAIA0AAOwDACAOAADtAwAgvQECAAAAAcEBQAAAAAHCAUAAAAAB0AEBAAAAAeIBAAAA7wEC7AEBAAAAAe0BCAAAAAECAAAAQQAgHgAA0AQAIAMAAAADACAeAADQBAAgHwAA1AQAIA0AAAADACABAAC4AwAgCAAAuQMAIA0AALoDACAOAAC7AwAgFwAA1AQAIL0BAgD1AgAhwQFAAOICACHCAUAA4gIAIdABAQDhAgAh4gEAALcD7wEi7AEBAOECACHtAQgAtgMAIQsBAAC4AwAgCAAAuQMAIA0AALoDACAOAAC7AwAgvQECAPUCACHBAUAA4gIAIcIBQADiAgAh0AEBAOECACHiAQAAtwPvASLsAQEA4QIAIe0BCAC2AwAhCwEAAOoDACAIAADrAwAgDgAA7QMAIA8AAO4DACC9AQIAAAABwQFAAAAAAcIBQAAAAAHQAQEAAAAB4gEAAADvAQLsAQEAAAAB7QEIAAAAAQIAAABBACAeAADVBAAgDQQAAK0EACAOAACvBAAgEAAAsAQAIBEAALEEACC9AQEAAAABwQFAAAAAAcIBQAAAAAHiAQAAAPQBAugBAQAAAAHvAQEAAAAB8QEAAADxAQLyAQEAAAAB9AEgAAAAAQIAAAABACAeAADXBAAgAwAAAAMAIB4AANUEACAfAADbBAAgDQAAAAMAIAEAALgDACAIAAC5AwAgDgAAuwMAIA8AALwDACAXAADbBAAgvQECAPUCACHBAUAA4gIAIcIBQADiAgAh0AEBAOECACHiAQAAtwPvASLsAQEA4QIAIe0BCAC2AwAhCwEAALgDACAIAAC5AwAgDgAAuwMAIA8AALwDACC9AQIA9QIAIcEBQADiAgAhwgFAAOICACHQAQEA4QIAIeIBAAC3A-8BIuwBAQDhAgAh7QEIALYDACEDAAAAKwAgHgAA1wQAIB8AAN4EACAPAAAAKwAgBAAA-QMAIA4AAPsDACAQAAD8AwAgEQAA_QMAIBcAAN4EACC9AQEA4QIAIcEBQADiAgAhwgFAAOICACHiAQAA9wP0ASLoAQEA5wIAIe8BAQDhAgAh8QEAAPYD8QEi8gEBAOcCACH0ASAA-AMAIQ0EAAD5AwAgDgAA-wMAIBAAAPwDACARAAD9AwAgvQEBAOECACHBAUAA4gIAIcIBQADiAgAh4gEAAPcD9AEi6AEBAOcCACHvAQEA4QIAIfEBAAD2A_EBIvIBAQDnAgAh9AEgAPgDACEICQAAigMAIAoAAIsDACC9AQIAAAABwQFAAAAAAd0BAQAAAAHeAQIAAAAB4AFAAAAAAeIBAAAA4gECAgAAAA0AIB4AAN8EACALAQAA6gMAIAgAAOsDACANAADsAwAgDwAA7gMAIL0BAgAAAAHBAUAAAAABwgFAAAAAAdABAQAAAAHiAQAAAO8BAuwBAQAAAAHtAQgAAAABAgAAAEEAIB4AAOEEACANBAAArQQAIA0AAK4EACAQAACwBAAgEQAAsQQAIL0BAQAAAAHBAUAAAAABwgFAAAAAAeIBAAAA9AEC6AEBAAAAAe8BAQAAAAHxAQAAAPEBAvIBAQAAAAH0ASAAAAABAgAAAAEAIB4AAOMEACADAAAACwAgHgAA3wQAIB8AAOcEACAKAAAACwAgCQAAggMAIAoAAIMDACAXAADnBAAgvQECAPUCACHBAUAA4gIAId0BAQDhAgAh3gECAPUCACHgAUAA4gIAIeIBAACBA-IBIggJAACCAwAgCgAAgwMAIL0BAgD1AgAhwQFAAOICACHdAQEA4QIAId4BAgD1AgAh4AFAAOICACHiAQAAgQPiASIDAAAAAwAgHgAA4QQAIB8AAOoEACANAAAAAwAgAQAAuAMAIAgAALkDACANAAC6AwAgDwAAvAMAIBcAAOoEACC9AQIA9QIAIcEBQADiAgAhwgFAAOICACHQAQEA4QIAIeIBAAC3A-8BIuwBAQDhAgAh7QEIALYDACELAQAAuAMAIAgAALkDACANAAC6AwAgDwAAvAMAIL0BAgD1AgAhwQFAAOICACHCAUAA4gIAIdABAQDhAgAh4gEAALcD7wEi7AEBAOECACHtAQgAtgMAIQMAAAArACAeAADjBAAgHwAA7QQAIA8AAAArACAEAAD5AwAgDQAA-gMAIBAAAPwDACARAAD9AwAgFwAA7QQAIL0BAQDhAgAhwQFAAOICACHCAUAA4gIAIeIBAAD3A_QBIugBAQDnAgAh7wEBAOECACHxAQAA9gPxASLyAQEA5wIAIfQBIAD4AwAhDQQAAPkDACANAAD6AwAgEAAA_AMAIBEAAP0DACC9AQEA4QIAIcEBQADiAgAhwgFAAOICACHiAQAA9wP0ASLoAQEA5wIAIe8BAQDhAgAh8QEAAPYD8QEi8gEBAOcCACH0ASAA-AMAIQ0EAACtBAAgDQAArgQAIA4AAK8EACARAACxBAAgvQEBAAAAAcEBQAAAAAHCAUAAAAAB4gEAAAD0AQLoAQEAAAAB7wEBAAAAAfEBAAAA8QEC8gEBAAAAAfQBIAAAAAECAAAAAQAgHgAA7gQAIAMAAAArACAeAADuBAAgHwAA8gQAIA8AAAArACAEAAD5AwAgDQAA-gMAIA4AAPsDACARAAD9AwAgFwAA8gQAIL0BAQDhAgAhwQFAAOICACHCAUAA4gIAIeIBAAD3A_QBIugBAQDnAgAh7wEBAOECACHxAQAA9gPxASLyAQEA5wIAIfQBIAD4AwAhDQQAAPkDACANAAD6AwAgDgAA-wMAIBEAAP0DACC9AQEA4QIAIcEBQADiAgAhwgFAAOICACHiAQAA9wP0ASLoAQEA5wIAIe8BAQDhAgAh8QEAAPYD8QEi8gEBAOcCACH0ASAA-AMAIQ0EAACtBAAgDQAArgQAIA4AAK8EACAQAACwBAAgvQEBAAAAAcEBQAAAAAHCAUAAAAAB4gEAAAD0AQLoAQEAAAAB7wEBAAAAAfEBAAAA8QEC8gEBAAAAAfQBIAAAAAECAAAAAQAgHgAA8wQAIAMAAAArACAeAADzBAAgHwAA9wQAIA8AAAArACAEAAD5AwAgDQAA-gMAIA4AAPsDACAQAAD8AwAgFwAA9wQAIL0BAQDhAgAhwQFAAOICACHCAUAA4gIAIeIBAAD3A_QBIugBAQDnAgAh7wEBAOECACHxAQAA9gPxASLyAQEA5wIAIfQBIAD4AwAhDQQAAPkDACANAAD6AwAgDgAA-wMAIBAAAPwDACC9AQEA4QIAIcEBQADiAgAhwgFAAOICACHiAQAA9wP0ASLoAQEA5wIAIe8BAQDhAgAh8QEAAPYD8QEi8gEBAOcCACH0ASAA-AMAIQYEBAIGAAwNHAYOHQcQIQoRJQsGAQABBgAJCAgDDQ4GDhMHDxcIAgQAAgcABAIFCQMGAAUBBQoAAwkAAQoAAgwQBwMJAAEKAAILAAYBCgACBAgYAA0ZAA4aAA8bAAEBAAEBAQABBA0mAA4nABAoABEpAAAAAAMGABEkABIlABMAAAADBgARJAASJQATAQEAAQEBAAEFBgAYJAAbJQAcNgAZNwAaAAAAAAAFBgAYJAAbJQAcNgAZNwAaAAAFBgAhJAAkJQAlNgAiNwAjAAAAAAAFBgAhJAAkJQAlNgAiNwAjAgQAAgcABAIEAAIHAAQFBgAqJAAtJQAuNgArNwAsAAAAAAAFBgAqJAAtJQAuNgArNwAsAQoAAgEKAAIFBgAzJAA2JQA3NgA0NwA1AAAAAAAFBgAzJAA2JQA3NgA0NwA1AgkAAQoAAgIJAAEKAAIFBgA8JAA_JQBANgA9NwA-AAAAAAAFBgA8JAA_JQBANgA9NwA-AwkAAQoAAgsABgMJAAEKAAILAAYFBgBFJABIJQBJNgBGNwBHAAAAAAAFBgBFJABIJQBJNgBGNwBHAQEAAQEBAAEDBgBOJABPJQBQAAAAAwYATiQATyUAUAEBAAEBAQABAwYAVSQAViUAVwAAAAMGAFUkAFYlAFcAAAADBgBdJABeJQBfAAAAAwYAXSQAXiUAXxICARMqARQtARUuARYvARgxARkzDRo0Dhs2ARw4DR05DyA6ASE7ASI8DSY_ECdAFChCAilDAipFAitGAixHAi1JAi5LDS9MFTBOAjFQDTJRFjNSAjRTAjVUDThXFzlYHTpaBDtbBDxeBD1fBD5gBD9iBEBkDUFlHkJnBENpDURqH0VrBEZsBEdtDUhwIElxJkpyA0tzA0x0A011A052A094A1B6DVF7J1J9A1N_DVSAAShVgQEDVoIBA1eDAQ1YhgEpWYcBL1qIAQhbiQEIXIoBCF2LAQhejAEIX44BCGCQAQ1hkQEwYpMBCGOVAQ1klgExZZcBCGaYAQhnmQENaJwBMmmdAThqngEGa58BBmygAQZtoQEGbqIBBm-kAQZwpgENcacBOXKpAQZzqwENdKwBOnWtAQZ2rgEGd68BDXiyATt5swFBerQBB3u1AQd8tgEHfbcBB364AQd_ugEHgAG8AQ2BAb0BQoIBvwEHgwHBAQ2EAcIBQ4UBwwEHhgHEAQeHAcUBDYgByAFEiQHJAUqKAcoBCosBywEKjAHMAQqNAc0BCo4BzgEKjwHQAQqQAdIBDZEB0wFLkgHVAQqTAdcBDZQB2AFMlQHZAQqWAdoBCpcB2wENmAHeAU2ZAd8BUZoB4AELmwHhAQucAeIBC50B4wELngHkAQufAeYBC6AB6AENoQHpAVKiAesBC6MB7QENpAHuAVOlAe8BC6YB8AELpwHxAQ2oAfQBVKkB9QFYqgH3AVmrAfgBWawB-wFZrQH8AVmuAf0BWa8B_wFZsAGBAg2xAYICWrIBhAJZswGGAg20AYcCW7UBiAJZtgGJAlm3AYoCDbgBjQJcuQGOAmA"
};
async function decodeBase64AsWasm(wasmBase64) {
  const { Buffer } = await import("buffer");
  const wasmArray = Buffer.from(wasmBase64, "base64");
  return new WebAssembly.Module(wasmArray);
}
config.compilerWasm = {
  getRuntime: async () => await import("@prisma/client/runtime/query_compiler_fast_bg.postgresql.mjs"),
  getQueryCompilerWasmModule: async () => {
    const { wasm } = await import("@prisma/client/runtime/query_compiler_fast_bg.postgresql.wasm-base64.mjs");
    return await decodeBase64AsWasm(wasm);
  },
  importName: "./query_compiler_fast_bg.js"
};
function getPrismaClientClass() {
  return runtime.getPrismaClient(config);
}

// generated/prisma/internal/prismaNamespace.ts
import * as runtime2 from "@prisma/client/runtime/client";
var getExtensionContext = runtime2.Extensions.getExtensionContext;
var NullTypes2 = {
  DbNull: runtime2.NullTypes.DbNull,
  JsonNull: runtime2.NullTypes.JsonNull,
  AnyNull: runtime2.NullTypes.AnyNull
};
var TransactionIsolationLevel = runtime2.makeStrictEnum({
  ReadUncommitted: "ReadUncommitted",
  ReadCommitted: "ReadCommitted",
  RepeatableRead: "RepeatableRead",
  Serializable: "Serializable"
});
var defineExtension = runtime2.Extensions.defineExtension;

// generated/prisma/client.ts
globalThis["__dirname"] = path.dirname(fileURLToPath(import.meta.url));
var PrismaClient = getPrismaClientClass();

// src/lib/prisma.ts
var connectionString = process.env.DATABASE_URL;
var adapter = new PrismaPg({
  connectionString
});
var prisma = new PrismaClient({ adapter });

// src/lib/auth.ts
var baseURL = process.env.BETTER_AUTH_URL ?? process.env.APP_URL;
var trustedOrigins = process.env.APP_URL ? [process.env.APP_URL] : [];
var auth = betterAuth({
  basePath: "/api/auth",
  ...baseURL && { baseURL },
  database: prismaAdapter(prisma, {
    provider: "postgresql"
  }),
  ...trustedOrigins.length > 0 && { trustedOrigins },
  user: {
    additionalFields: {
      role: {
        type: "string",
        defaultValue: "STUDENT",
        required: false
      },
      status: {
        type: "string",
        defaultValue: "ACTIVE",
        required: false
      }
    }
  },
  emailAndPassword: {
    enabled: true,
    autoSignIn: true,
    requireEmailVerification: false
  },
  socialProviders: {
    google: {
      prompt: "select_account",
      clientId: process.env.GOOGLE_CLIENT_ID,
      clientSecret: process.env.GOOGLE_CLIENT_SECRET,
      accessType: "offline"
    }
  }
});

// src/modules/admin/admin.route.ts
import express from "express";

// src/modules/admin/admin.service.ts
var getAllUsers = async () => {
  return prisma.user.findMany({
    select: {
      id: true,
      email: true,
      name: true,
      role: true,
      status: true,
      image: true,
      createdAt: true,
      updatedAt: true,
      tutorProfile: {
        select: {
          id: true,
          bio: true,
          hourlyRate: true,
          status: true,
          categories: { include: { category: true } }
        }
      }
    },
    orderBy: { createdAt: "desc" }
  });
};
var updateUserStatus = async (userId, status) => {
  return prisma.user.update({
    where: { id: userId },
    data: { status },
    select: {
      id: true,
      email: true,
      name: true,
      role: true,
      status: true,
      createdAt: true,
      updatedAt: true
    }
  });
};
var getAllBookings = async () => {
  return prisma.booking.findMany({
    include: {
      student: { select: { id: true, name: true, email: true } },
      tutor: {
        include: {
          user: true,
          categories: { include: { category: true } }
        }
      }
    },
    orderBy: { scheduledAt: "desc" }
  });
};
var getAllCategoriesAdmin = async () => {
  return prisma.category.findMany({
    orderBy: { name: "asc" },
    include: {
      _count: { select: { tutors: true } }
    }
  });
};
var createCategory = async (name) => {
  return prisma.category.create({
    data: { name }
  });
};
var updateCategory = async (id, name) => {
  return prisma.category.update({
    where: { id },
    data: { name }
  });
};
var deleteCategory = async (id) => {
  await prisma.tutorCategory.deleteMany({ where: { categoryId: id } });
  return prisma.category.delete({
    where: { id }
  });
};
var adminService = {
  getAllUsers,
  updateUserStatus,
  getAllBookings,
  getAllCategoriesAdmin,
  createCategory,
  updateCategory,
  deleteCategory
};

// src/modules/admin/admin.controller.ts
var getAllUsers2 = async (req, res, next) => {
  try {
    const result = await adminService.getAllUsers();
    res.status(200).json({ success: true, data: result });
  } catch (error) {
    next(error);
  }
};
var updateUserStatus2 = async (req, res, next) => {
  try {
    const { id } = req.params;
    const { status } = req.body;
    if (!["ACTIVE", "BANNED"].includes(status)) {
      return res.status(400).json({
        success: false,
        message: "status must be ACTIVE or BANNED"
      });
    }
    const result = await adminService.updateUserStatus(id, status);
    res.status(200).json({ success: true, data: result });
  } catch (error) {
    next(error);
  }
};
var getAllBookings2 = async (req, res, next) => {
  try {
    const result = await adminService.getAllBookings();
    res.status(200).json({ success: true, data: result });
  } catch (error) {
    next(error);
  }
};
var getCategories = async (req, res, next) => {
  try {
    const result = await adminService.getAllCategoriesAdmin();
    res.status(200).json({ success: true, data: result });
  } catch (error) {
    next(error);
  }
};
var createCategory2 = async (req, res, next) => {
  try {
    const { name } = req.body;
    console.log(req.body, "body");
    if (!name || typeof name !== "string") {
      return res.status(400).json({
        success: false,
        message: "name is required"
      });
    }
    const result = await adminService.createCategory(name.trim());
    res.status(201).json({ success: true, data: result });
  } catch (error) {
    next(error);
  }
};
var updateCategory2 = async (req, res, next) => {
  try {
    const id = Number(req.params.id);
    const { name } = req.body;
    if (!name || typeof name !== "string") {
      return res.status(400).json({
        success: false,
        message: "name is required"
      });
    }
    const result = await adminService.updateCategory(id, name.trim());
    res.status(200).json({ success: true, data: result });
  } catch (error) {
    next(error);
  }
};
var deleteCategory2 = async (req, res, next) => {
  try {
    const id = Number(req.params.id);
    await adminService.deleteCategory(id);
    res.status(200).json({ success: true, message: "Category deleted" });
  } catch (error) {
    next(error);
  }
};
var adminController = {
  getAllUsers: getAllUsers2,
  updateUserStatus: updateUserStatus2,
  getAllBookings: getAllBookings2,
  getCategories,
  createCategory: createCategory2,
  updateCategory: updateCategory2,
  deleteCategory: deleteCategory2
};

// src/middleware/authMiddleware.ts
var authMiddleware = (...roles) => {
  return async (req, res, next) => {
    try {
      const session = await auth.api.getSession({
        headers: req.headers
      });
      if (!session) {
        return res.status(401).json({ message: "Unauthorized" });
      }
      const dbUser = await prisma.user.findUnique({
        where: { id: session.user.id },
        select: { status: true }
      });
      if (dbUser?.status === "BANNED") {
        return res.status(403).json({ message: "Account is suspended" });
      }
      req.user = {
        id: session.user.id,
        name: session.user.name,
        email: session.user.email,
        role: session.user.role
      };
      if (roles.length && !roles.includes(req.user.role)) {
        return res.status(403).json({ message: "Forbidden Access" });
      }
      next();
    } catch (error) {
      next(error);
    }
  };
};
var authMiddleware_default = authMiddleware;

// src/modules/admin/admin.route.ts
var router = express.Router();
router.get(
  "/users",
  authMiddleware_default("ADMIN" /* ADMIN */),
  adminController.getAllUsers
);
router.patch(
  "/users/:id",
  authMiddleware_default("ADMIN" /* ADMIN */),
  adminController.updateUserStatus
);
router.get("/bookings", adminController.getAllBookings);
router.get("/categories", adminController.getCategories);
router.post(
  "/categories",
  authMiddleware_default("ADMIN" /* ADMIN */),
  adminController.createCategory
);
router.patch(
  "/categories/:id",
  authMiddleware_default("ADMIN" /* ADMIN */),
  adminController.updateCategory
);
router.delete(
  "/categories/:id",
  authMiddleware_default("ADMIN" /* ADMIN */),
  adminController.deleteCategory
);
var adminRouter = router;

// src/modules/booking/booking.route.ts
import express2 from "express";

// src/modules/booking/booking.service.ts
var createBooking = async (studentId, data) => {
  return prisma.booking.create({
    data: {
      studentId,
      tutorId: data.tutorId,
      scheduledAt: data.scheduledAt,
      status: "PENDING"
    },
    include: {
      tutor: {
        include: {
          user: true,
          categories: { include: { category: true } }
        }
      },
      student: { select: { id: true, name: true, email: true } }
    }
  });
};
var getBookingsByUser = async (userId, role) => {
  if (role === "TUTOR") {
    const profile = await prisma.tutorProfile.findUnique({
      where: { userId },
      select: { id: true }
    });
    if (!profile) return [];
    return prisma.booking.findMany({
      where: { tutorId: profile.id },
      include: {
        student: { select: { id: true, name: true, email: true } },
        tutor: {
          include: {
            user: true,
            categories: { include: { category: true } }
          }
        }
      },
      orderBy: { scheduledAt: "desc" }
    });
  }
  return prisma.booking.findMany({
    where: { studentId: userId },
    include: {
      tutor: {
        include: {
          user: true,
          categories: { include: { category: true } }
        }
      },
      student: { select: { id: true, name: true, email: true } }
    },
    orderBy: { scheduledAt: "desc" }
  });
};
var getBookingById = async (id, userId, role) => {
  const booking = await prisma.booking.findUnique({
    where: { id },
    include: {
      tutor: {
        include: {
          user: true,
          categories: { include: { category: true } }
        }
      },
      student: { select: { id: true, name: true, email: true } }
    }
  });
  if (!booking) return null;
  if (role === "ADMIN") return booking;
  if (role === "TUTOR") {
    const profile = await prisma.tutorProfile.findUnique({
      where: { userId },
      select: { id: true }
    });
    if (profile?.id === booking.tutorId) return booking;
  }
  if (booking.studentId === userId) return booking;
  return null;
};
var updateBookingStatus = async (id, status, userId, role) => {
  const booking = await prisma.booking.findUnique({ where: { id } });
  if (!booking) return null;
  if (role === "TUTOR") {
    const profile = await prisma.tutorProfile.findUnique({
      where: { userId },
      select: { id: true }
    });
    if (profile?.id !== booking.tutorId) return null;
  } else if (role !== "ADMIN" && booking.studentId !== userId) {
    return null;
  }
  return prisma.booking.update({
    where: { id },
    data: { status },
    include: {
      tutor: { include: { user: true } },
      student: { select: { id: true, name: true, email: true } }
    }
  });
};
var getBookingsByTutorId = async (tutorId) => {
  return prisma.booking.findMany({
    where: { tutorId: Number(tutorId) },
    include: {
      student: true,
      tutor: true
    },
    orderBy: { createdAt: "desc" }
  });
};
var bookingService = {
  createBooking,
  getBookingsByUser,
  getBookingById,
  getBookingsByTutorId,
  updateBookingStatus
};

// src/modules/booking/booking.controller.ts
var createBooking2 = async (req, res, next) => {
  try {
    const user = req.user;
    if (!user) {
      return res.status(401).json({ success: false, message: "Unauthorized" });
    }
    const { tutorId, scheduledAt } = req.body;
    if (!tutorId || !scheduledAt) {
      return res.status(400).json({
        success: false,
        message: "tutorId and scheduledAt are required"
      });
    }
    const result = await bookingService.createBooking(user.id, {
      tutorId: Number(tutorId),
      scheduledAt: new Date(scheduledAt)
    });
    res.status(201).json({ success: true, data: result });
  } catch (error) {
    next(error);
  }
};
var getBookings = async (req, res, next) => {
  try {
    const user = req.user;
    if (!user) {
      return res.status(401).json({ success: false, message: "Unauthorized" });
    }
    const result = await bookingService.getBookingsByUser(user.id, user.role);
    res.status(200).json({ success: true, data: result });
  } catch (error) {
    next(error);
  }
};
var getBookingById2 = async (req, res, next) => {
  try {
    const user = req.user;
    if (!user) {
      return res.status(401).json({ success: false, message: "Unauthorized" });
    }
    const id = Number(req.params.id);
    const result = await bookingService.getBookingById(id, user.id, user.role);
    if (!result) {
      return res.status(404).json({ success: false, message: "Booking not found" });
    }
    res.status(200).json({ success: true, data: result });
  } catch (error) {
    next(error);
  }
};
var getMyBookings = async (req, res, next) => {
  try {
    if (!req.user) {
      return res.status(401).json({ success: false, message: "Unauthorized" });
    }
    const tutorId = req.user.id;
    const bookings = await bookingService.getBookingsByTutorId(tutorId);
    res.status(200).json({ success: true, data: bookings });
  } catch (err) {
    next(err);
  }
};
var updateBookingStatus2 = async (req, res, next) => {
  try {
    const user = req.user;
    if (!user) {
      return res.status(401).json({ success: false, message: "Unauthorized" });
    }
    const id = Number(req.params.id);
    const { status } = req.body;
    if (!["CONFIRMED", "COMPLETED", "CANCELLED"].includes(status)) {
      return res.status(400).json({
        success: false,
        message: "status must be CONFIRMED, COMPLETED, or CANCELLED"
      });
    }
    const result = await bookingService.updateBookingStatus(
      id,
      status,
      user.id,
      user.role
    );
    if (!result) {
      return res.status(404).json({ success: false, message: "Booking not found" });
    }
    res.status(200).json({ success: true, data: result });
  } catch (error) {
    next(error);
  }
};
var bookingController = {
  createBooking: createBooking2,
  getBookings,
  getMyBookings,
  getBookingById: getBookingById2,
  updateBookingStatus: updateBookingStatus2
};

// src/modules/booking/booking.route.ts
var router2 = express2.Router();
router2.post(
  "/",
  authMiddleware_default("STUDENT" /* STUDENT */),
  bookingController.createBooking
);
router2.get(
  "/tutor/me",
  authMiddleware_default("TUTOR" /* TUTOR */, "STUDENT" /* STUDENT */),
  bookingController.getBookings
);
router2.get(
  "/:id",
  authMiddleware_default("TUTOR" /* TUTOR */, "STUDENT" /* STUDENT */),
  bookingController.getBookingById
);
router2.patch(
  "/:id/status",
  authMiddleware_default("TUTOR" /* TUTOR */),
  bookingController.updateBookingStatus
);
var bookingRouter = router2;

// src/modules/user/user.route.ts
import express3 from "express";

// src/modules/user/user.service.ts
var getAllUsers3 = async () => {
  return prisma.user.findMany({
    select: {
      id: true,
      name: true,
      email: true,
      role: true,
      status: true
    }
  });
};
var updateUserProfile = async (id, data) => {
  return prisma.user.update({
    where: { id },
    data,
    select: {
      id: true,
      name: true,
      email: true,
      role: true,
      status: true
    }
  });
};
var getUserById = async (id) => {
  return prisma.user.findUnique({
    where: { id },
    select: {
      id: true,
      name: true,
      email: true,
      role: true,
      status: true
    }
  });
};
var userService = {
  getAllUsers: getAllUsers3,
  updateUserProfile,
  getUserById
};

// src/modules/user/user.controller.ts
var getAllUsersController = async (req, res) => {
  try {
    const users = await userService.getAllUsers();
    res.status(200).json({
      success: true,
      data: users
    });
  } catch {
    res.status(500).json({
      success: false,
      message: "Server error"
    });
  }
};
var updateUserProfileController = async (req, res, next) => {
  try {
    const userId = req.user?.id;
    if (!userId) {
      return res.status(401).json({ success: false, message: "Unauthorized" });
    }
    const { name, email } = req.body;
    if (email && typeof email !== "string") {
      return res.status(400).json({ success: false, message: "Invalid email format" });
    }
    if (name && typeof name !== "string") {
      return res.status(400).json({ success: false, message: "Invalid name format" });
    }
    const updatedUser = await userService.updateUserProfile(userId, {
      name,
      email
    });
    res.status(200).json({
      success: true,
      data: updatedUser
    });
  } catch (error) {
    next(error);
  }
};
var getLoggedInUserController = async (req, res) => {
  try {
    const userId = req.user.id;
    const user = await userService.getUserById(userId);
    if (!user) {
      return res.status(404).json({
        success: false,
        message: "User not found"
      });
    }
    res.status(200).json({
      success: true,
      data: user
    });
  } catch {
    res.status(500).json({
      success: false,
      message: "Server error"
    });
  }
};
var userController = {
  getAllUsersController,
  updateUserProfileController,
  getLoggedInUserController
};

// src/modules/user/user.route.ts
var router3 = express3.Router();
router3.get("/", userController.getAllUsersController);
router3.get("/me", authMiddleware_default(), userController.getLoggedInUserController);
router3.patch(
  "/update",
  authMiddleware_default(),
  userController.updateUserProfileController
);
var userRouter = router3;

// src/modules/tutors/tutor.route.ts
import express4 from "express";

// src/modules/tutors/tutors.service.ts
var createTutorProfile = async (userId, data) => {
  const categoryIds = [...new Set(data.categoryIds ?? [])];
  return prisma.$transaction(async (tx) => {
    const existing = await tx.tutorProfile.findUnique({
      where: { userId }
    });
    if (existing) {
      throw new Error("Your profile already exists");
    }
    const profile = await tx.tutorProfile.create({
      data: {
        userId,
        bio: data.bio,
        hourlyRate: data.hourlyRate,
        status: data.status
      }
    });
    if (categoryIds.length) {
      await tx.tutorCategory.createMany({
        data: categoryIds.map((categoryId) => ({
          tutorProfileId: profile.id,
          categoryId
        })),
        skipDuplicates: true
      });
    }
    return tx.tutorProfile.findUnique({
      where: { id: profile.id },
      include: {
        user: true,
        categories: { include: { category: true } }
      }
    });
  });
};
var getAllTutors = async (filters) => {
  const where = {};
  if (filters?.categoryId) {
    where.categories = {
      some: { categoryId: filters.categoryId }
    };
  }
  if (filters?.maxPrice) {
    where.hourlyRate = { lte: filters.maxPrice };
  }
  const tutors = await prisma.tutorProfile.findMany({
    where,
    include: {
      user: true,
      categories: { include: { category: true } },
      reviews: true,
      availability: true
    }
  });
  if (filters?.minRating) {
    return tutors.filter((t) => {
      if (!t.reviews.length) return false;
      const avg = t.reviews.reduce((s, r) => s + r.rating, 0) / t.reviews.length;
      return avg >= filters.minRating;
    });
  }
  return tutors;
};
var getTutorById = async (tutorId) => {
  return prisma.tutorProfile.findUnique({
    where: { id: tutorId },
    include: {
      user: true,
      categories: { include: { category: true } },
      reviews: { include: { student: true } }
    }
  });
};
var getAllTutorProfiles = async () => {
  const profiles = await prisma.tutorProfile.findMany({
    include: {
      user: true,
      categories: { include: { category: true } }
    }
  });
  return profiles.map((profile) => ({
    id: profile.id,
    bio: profile.bio,
    hourlyRateCents: profile.hourlyRate,
    status: profile.status,
    categoryIds: profile.categories.map((c) => c.category.id),
    user: {
      id: profile.user.id,
      email: profile.user.email,
      name: profile.user.name
    }
  }));
};
var getTutorByUserId = async (userId) => {
  const profile = await prisma.tutorProfile.findUnique({
    where: { userId },
    include: {
      categories: {
        include: {
          category: true
        }
      }
    }
  });
  if (!profile) return null;
  return {
    id: profile.id,
    bio: profile.bio,
    hourlyRateCents: profile.hourlyRate,
    status: profile.status,
    categoryIds: profile.categories.map((c) => c.category.id)
  };
};
var updateTutorProfile = async (userId, data) => {
  const profile = await prisma.tutorProfile.findUnique({
    where: { userId },
    select: { id: true }
  });
  if (!profile) throw new Error("Profile not found");
  const categoryIds = [...new Set(data.categoryIds ?? [])];
  return prisma.$transaction(async (tx) => {
    if (data.categoryIds) {
      await tx.tutorCategory.deleteMany({
        where: { tutorProfileId: profile.id }
      });
      if (categoryIds.length) {
        await tx.tutorCategory.createMany({
          data: categoryIds.map((categoryId) => ({
            tutorProfileId: profile.id,
            categoryId
          })),
          skipDuplicates: true
        });
      }
    }
    return tx.tutorProfile.update({
      where: { id: profile.id },
      data: {
        ...data.bio && { bio: data.bio },
        ...data.hourlyRate && { hourlyRate: data.hourlyRate },
        ...data.status && { status: data.status }
      },
      include: {
        user: true,
        categories: { include: { category: true } },
        availability: true
      }
    });
  });
};
var setAvailability = async (userId, slots) => {
  const profile = await prisma.tutorProfile.findUnique({
    where: { userId },
    select: { id: true }
  });
  if (!profile) throw new Error("Profile not found");
  return prisma.$transaction(async (tx) => {
    await tx.tutorAvailability.deleteMany({
      where: { tutorId: profile.id }
    });
    if (slots.length) {
      await tx.tutorAvailability.createMany({
        data: slots.map((s) => ({
          tutorId: profile.id,
          dayOfWeek: s.dayOfWeek,
          startTime: s.startTime,
          endTime: s.endTime
        }))
      });
    }
    return tx.tutorAvailability.findMany({
      where: { tutorId: profile.id },
      orderBy: { dayOfWeek: "asc" }
    });
  });
};
var tutorsService = {
  createTutorProfile,
  getAllTutors,
  getTutorById,
  getTutorByUserId,
  getAllTutorProfiles,
  updateTutorProfile,
  setAvailability
};

// src/modules/tutors/tutors.controller.ts
var createTutorProfile2 = async (req, res, next) => {
  try {
    const user = req.user;
    if (!user) {
      return res.status(401).json({
        success: false,
        message: "Unauthorized"
      });
    }
    const body = req.body;
    const categoryIds = Array.isArray(body.categoryIds) ? body.categoryIds.map(Number) : [];
    const result = await tutorsService.createTutorProfile(user.id, {
      bio: body.bio,
      hourlyRate: body.hourlyRate,
      status: body.status,
      categoryIds
    });
    res.status(201).json({
      success: true,
      data: result
    });
  } catch (error) {
    next(error);
  }
};
var getAllTutors2 = async (req, res, next) => {
  try {
    const categoryId = req.query.categoryId ? Number(req.query.categoryId) : void 0;
    const minRating = req.query.minRating ? Number(req.query.minRating) : void 0;
    const maxPrice = req.query.maxPrice ? Number(req.query.maxPrice) : void 0;
    const filters = {};
    if (categoryId != null) filters.categoryId = categoryId;
    if (minRating != null) filters.minRating = minRating;
    if (maxPrice != null) filters.maxPrice = maxPrice;
    const result = await tutorsService.getAllTutors(filters);
    res.status(200).json({
      success: true,
      data: result
    });
  } catch (error) {
    next(error);
  }
};
var getTutorProfileById = async (req, res, next) => {
  try {
    const tutorId = Number(req.params.id);
    if (Number.isNaN(tutorId)) {
      return res.status(400).json({ message: "Invalid tutor id" });
    }
    const result = await tutorsService.getTutorById(tutorId);
    if (!result) {
      return res.status(404).json({ message: "Tutor not found" });
    }
    res.json({ success: true, data: result });
  } catch (e) {
    next(e);
  }
};
var getAllTutorProfilesController = async (req, res, next) => {
  try {
    const profiles = await tutorsService.getAllTutorProfiles();
    res.status(200).json({ success: true, data: profiles });
  } catch (err) {
    next(err);
  }
};
var getMyTutorProfile = async (req, res, next) => {
  try {
    if (!req.user) {
      return res.status(401).json({ success: false, message: "Unauthorized" });
    }
    const userId = req.user.id;
    const result = await tutorsService.getTutorByUserId(userId);
    if (!result) {
      return res.status(200).json({ success: true, data: null });
    }
    res.status(200).json({
      success: true,
      data: result
    });
  } catch (error) {
    next(error);
  }
};
var updateTutorProfile2 = async (req, res, next) => {
  try {
    const user = req.user;
    if (!user) {
      return res.status(401).json({ success: false, message: "Unauthorized" });
    }
    const body = req.body;
    const categoryIds = Array.isArray(body.categoryIds) ? body.categoryIds.map(Number) : void 0;
    const result = await tutorsService.updateTutorProfile(user.id, {
      bio: body.bio,
      hourlyRate: body.hourlyRate,
      status: body.status,
      categoryIds
    });
    if (!result) {
      return res.status(404).json({
        success: false,
        message: "Tutor profile not found"
      });
    }
    res.status(200).json({ success: true, data: result });
  } catch (error) {
    next(error);
  }
};
var setAvailability2 = async (req, res, next) => {
  try {
    const user = req.user;
    if (!user) {
      return res.status(401).json({ success: false, message: "Unauthorized" });
    }
    const slots = req.body.slots;
    if (!Array.isArray(slots)) {
      return res.status(400).json({
        success: false,
        message: "slots array is required"
      });
    }
    const result = await tutorsService.setAvailability(user.id, slots);
    if (!result) {
      return res.status(404).json({
        success: false,
        message: "Tutor profile not found"
      });
    }
    res.status(200).json({ success: true, data: result });
  } catch (error) {
    next(error);
  }
};
var tutorsController = {
  createTutorProfile: createTutorProfile2,
  getAllTutors: getAllTutors2,
  getAllTutorProfilesController,
  getTutorProfileById,
  getMyTutorProfile,
  updateTutorProfile: updateTutorProfile2,
  setAvailability: setAvailability2
};

// src/modules/tutors/tutor.route.ts
var router4 = express4.Router();
router4.post(
  "/",
  authMiddleware_default("TUTOR" /* TUTOR */),
  tutorsController.createTutorProfile
);
router4.get("/", tutorsController.getAllTutors);
router4.get(
  "/me",
  authMiddleware_default("TUTOR" /* TUTOR */),
  tutorsController.getAllTutorProfilesController
);
router4.get(
  "/:id",
  tutorsController.getTutorProfileById
);
router4.put(
  "/profile",
  authMiddleware_default("TUTOR" /* TUTOR */),
  tutorsController.updateTutorProfile
);
router4.put(
  "/availability",
  authMiddleware_default("TUTOR" /* TUTOR */),
  tutorsController.setAvailability
);
var tutorRouter = router4;

// src/modules/review/review.route.ts
import express5 from "express";

// src/modules/review/review.service.ts
var createReview = async (studentId, data) => {
  if (data.rating < 1 || data.rating > 5) {
    throw new Error("Rating must be between 1 and 5");
  }
  if (!data.bookingId) {
    throw new Error("Booking ID is required to submit a review");
  }
  const booking = await prisma.booking.findUnique({
    where: { id: data.bookingId }
  });
  if (!booking) {
    throw new Error("Booking not found");
  }
  if (booking.studentId !== studentId) {
    throw new Error("You are not allowed to review this booking");
  }
  if (booking.tutorId !== data.tutorId) {
    throw new Error("Tutor mismatch for this booking");
  }
  if (booking.status !== "COMPLETED") {
    throw new Error("Only completed bookings can be reviewed");
  }
  const existingReview = await prisma.review.findFirst({
    where: {
      bookingId: data.bookingId
    }
  });
  if (existingReview) {
    throw new Error("You have already reviewed this booking");
  }
  const review = await prisma.review.create({
    data: {
      studentId,
      tutorId: data.tutorId,
      bookingId: data.bookingId,
      rating: data.rating,
      comment: data.comment ?? null
    },
    include: {
      student: {
        select: {
          id: true,
          name: true
        }
      },
      tutor: {
        include: {
          user: true
        }
      }
    }
  });
  return review;
};
var getReviewsForTutor = async (userId) => {
  const tutorProfile = await prisma.tutorProfile.findUnique({
    where: { userId }
  });
  if (!tutorProfile) {
    throw new Error("Tutor profile not found");
  }
  return prisma.review.findMany({
    where: { tutorId: tutorProfile.id },
    include: {
      student: {
        select: { id: true, name: true }
      }
    },
    orderBy: { createdAt: "desc" }
  });
};
var reviewService = {
  createReview,
  getReviewsForTutor
};

// src/modules/review/review.controller.ts
var createReview2 = async (req, res, next) => {
  try {
    const user = req.user;
    if (!user) {
      return res.status(401).json({ success: false, message: "Unauthorized" });
    }
    const { tutorId, bookingId, rating, comment } = req.body;
    if (!tutorId || rating == null) {
      return res.status(400).json({
        success: false,
        message: "tutorId and rating are required"
      });
    }
    const input = {
      tutorId: Number(tutorId),
      rating: Number(rating)
    };
    if (bookingId != null) input.bookingId = Number(bookingId);
    if (comment != null) input.comment = comment;
    const result = await reviewService.createReview(user.id, input);
    res.status(201).json({ success: true, data: result });
  } catch (error) {
    const message = error instanceof Error ? error.message : "Failed to create review";
    if (message.includes("already reviewed") || message.includes("Invalid or incomplete")) {
      return res.status(400).json({ success: false, message });
    }
    next(error);
  }
};
var getMyReviews = async (req, res, next) => {
  try {
    const user = req.user;
    if (!user) {
      return res.status(401).json({ success: false, message: "Unauthorized" });
    }
    const reviews = await reviewService.getReviewsForTutor(user.id);
    res.json({ success: true, data: reviews });
  } catch (error) {
    next(error);
  }
};
var reviewController = {
  createReview: createReview2,
  getMyReviews
};

// src/modules/review/review.route.ts
var router5 = express5.Router();
router5.post(
  "/",
  authMiddleware_default("STUDENT" /* STUDENT */),
  reviewController.createReview
);
router5.get("/", authMiddleware_default("TUTOR" /* TUTOR */), reviewController.getMyReviews);
var reviewRouter = router5;

// src/middleware/notFound.ts
function notFound(req, res) {
  res.status(404).json({
    message: "Route not found!",
    path: req.originalUrl,
    date: Date()
  });
}

// src/middleware/globalErrorHandler.ts
function errorHandler(err, _req, res, _next) {
  console.error("\u{1F525} FULL ERROR:", err);
  console.error("\u{1F525} STACK:", err?.stack);
  res.status(500).json({
    success: false,
    message: err?.message || "Internal Server Error"
  });
}

// src/app.ts
var app = express6();
app.use(
  cors({
    origin: process.env.APP_URL || "https://skill-bridge-client-ruby.vercel.app",
    credentials: true
  })
);
app.use(express6.json());
app.all("/api/auth/*splat", toNodeHandler(auth));
app.use("/api/user", userRouter);
app.use("/api/tutor", tutorRouter);
app.use("/api/bookings", bookingRouter);
app.use("/api/reviews", reviewRouter);
app.use("/api/admin", adminRouter);
app.get("/", (_req, res) => {
  res.send("SkillBridge API running");
});
app.use(notFound);
app.use(errorHandler);
var app_default = app;

// src/index.ts
var PORT = process.env.PORT || 5e3;
async function bootstrap() {
  try {
    await prisma.$connect();
    console.log("\u2705 Database connected");
    app_default.listen(PORT, () => {
      console.log(`\u{1F680} Server listening on port ${PORT}`);
    });
  } catch (error) {
    console.error("\u274C Server failed to start", error);
    await prisma.$disconnect();
    process.exit(1);
  }
}
bootstrap();
